var chapters = [
  { topic: "chapter", section: "1", title: "Introducing Oracle Net Services", anchor: "NETAG001", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Identifying and Accessing the Database", anchor: "NETAG002", file: "concepts.htm" },
  { topic: "chapter", section: "3", title: "Managing Network Address Information", anchor: "NETAG003", file: "config_concepts.htm" },
  { topic: "chapter", section: "4", title: "Understanding the Communication Layers", anchor: "NETAG004", file: "layers.htm" },
  { topic: "chapter", section: "5", title: "Understanding Oracle Net Architecture", anchor: "NETAG1511", file: "net_arch.htm" },
  { topic: "chapter", section: "6", title: "Quick Start to Oracle Net Services", anchor: "NETAG006", file: "gettingstart.htm" },
  { topic: "chapter", section: "7", title: "Managing Oracle Net Services", anchor: "NETAG005", file: "admintools.htm" },
  { topic: "chapter", section: "8", title: "Configuring Naming Methods", anchor: "NETAG008", file: "naming.htm" },
  { topic: "chapter", section: "9", title: "Configuring and Administering Oracle Net Listener", anchor: "NETAG010", file: "listenercfg.htm" },
  { topic: "chapter", section: "10", title: "Configuring Oracle Connection Manager", anchor: "NETAG011", file: "cman.htm" },
  { topic: "chapter", section: "11", title: "Configuring a Shared Server Architecture", anchor: "NETAG012", file: "dispatcher.htm" },
  { topic: "chapter", section: "12", title: "Configuring Profiles", anchor: "NETAG009", file: "profile.htm" },
  { topic: "chapter", section: "13", title: "Enabling Advanced Features of Oracle Net Services", anchor: "NETAG013", file: "advcfg.htm" },
  { topic: "chapter", section: "14", title: "Optimizing Performance", anchor: "NETAG014", file: "performance.htm" },
  { topic: "chapter", section: "15", title: "Testing Connections", anchor: "NETAG357", file: "connect.htm" },
  { topic: "chapter", section: "16", title: "Troubleshooting Oracle Net Services", anchor: "NETAG016", file: "trouble.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "NETAG1253", file: "glossary.htm" },
  { } ];
