var chapters = [
  { topic: "chapter", section: "", title: " Introduction to Oracle Label Security", anchor: "OLSAG001", file: "intro.htm" },
  { topic: "chapter", section: "", title: "Understanding Data Labels and User Labels", anchor: "OLSAG007", file: "labels.htm" },
  { topic: "chapter", section: "", title: " Access Controls and Privileges", anchor: "OLSAG013", file: "accpriv.htm" },
  { topic: "chapter", section: "", title: "Getting Started with Oracle Label Security", anchor: "OLSAG3721", file: "getting_started.htm" },
  { topic: "chapter", section: "", title: " Creating an Oracle Label Security Policy", anchor: "OLSAG3096", file: "getstrtd.htm" },
  { topic: "chapter", section: "", title: "  Working with Labeled Data", anchor: "OLSAG019", file: "worklabel.htm" },
  { topic: "chapter", section: "", title: " Oracle Label Security Using Oracle\u00A0Internet\u00A0Directory", anchor: "OLSAG026", file: "olsoid.htm" },
  { topic: "chapter", section: "", title: "  Implementing Policy Enforcement Options and Labeling Functions", anchor: "OLSAG055", file: "enforce.htm" },
  { topic: "chapter", section: "", title: "   Administering and Using Trusted Stored Program Units", anchor: "OLSAG068", file: "storproc.htm" },
  { topic: "chapter", section: "", title: " Auditing Under Oracle Label Security", anchor: "OLSAG073", file: "audit.htm" },
  { topic: "chapter", section: "", title: " Using Oracle Label Security with a Distributed Database", anchor: "OLSAG080", file: "multiple.htm" },
  { topic: "chapter", section: "", title: " Performing DBA Functions Under\u00A0Oracle\u00A0Label\u00A0Security", anchor: "OLSAG3416", file: "utilities.htm" },
  { topic: "chapter", section: "", title: " Releasability Using Inverse Groups", anchor: "OLSAG094", file: "releas.htm" },
  { topic: "appendix", section: "", title: "Disabling and Enabling Oracle Label Security", anchor: "OLSAG3794", file: "config.htm" },
  { topic: "appendix", section: "", title: " Advanced Topics in Oracle Label Security", anchor: "OLSAG104", file: "appxa.htm" },
  { topic: "appendix", section: "", title: "    Command-line Tools for Label Security Using Oracle Internet Directory ", anchor: "OLSAG108", file: "appxb.htm" },
  { topic: "appendix", section: "", title: " Oracle Label Security in an Oracle\u00A0RAC\u00A0Environment", anchor: "OLSAG3607", file: "appxd.htm" },
  { topic: "appendix", section: "", title: "Oracle Label Security PL/SQL Packages", anchor: "OLSAG3812", file: "packages.htm" },
  { topic: "appendix", section: "", title: "  Oracle Label Security Reference", anchor: "OLSAG113", file: "appc.htm" },
  { topic: "appendix", section: "", title: " Frequently Asked Questions about Oracle\u00A0Label Security", anchor: "OLSAG3611", file: "faq.htm" },
  { } ];
