var chapters = [
  { topic: "chapter", section: "1", title: "Datatypes for C", anchor: "CAXML00100", file: "datatypes.htm" },
  { topic: "chapter", section: "2", title: "Package Callback APIs for C", anchor: "CAXML00200", file: "callback.htm" },
  { topic: "chapter", section: "3", title: "Package DOM APIs for C", anchor: "CAXML00300", file: "dom.htm" },
  { topic: "chapter", section: "4", title: "Package Event APIs for C", anchor: "CAXML02000", file: "event.htm" },
  { topic: "chapter", section: "5", title: "Package Orastream APIs for C", anchor: "CAXML01400", file: "orastream.htm" },
  { topic: "chapter", section: "6", title: "Package Range APIs for C", anchor: "CAXML01000", file: "range.htm" },
  { topic: "chapter", section: "7", title: "Package SAX APIs for C", anchor: "CAXML5908", file: "sax.htm" },
  { topic: "chapter", section: "8", title: "Package Schema APIs for C", anchor: "CAXML05000", file: "schema.htm" },
  { topic: "chapter", section: "9", title: "Package SOAP APIs for C", anchor: "CAXML01300", file: "soap.htm" },
  { topic: "chapter", section: "10", title: "Package Traversal APIs for C", anchor: "CAXML01100", file: "traversal.htm" },
  { topic: "chapter", section: "11", title: "Package XML APIs for C", anchor: "CAXML6144", file: "xml.htm" },
  { topic: "chapter", section: "12", title: "Package XmlDiff APIs for C", anchor: "CAXML6192", file: "xmldiff.htm" },
  { topic: "chapter", section: "13", title: "Package XPath APIs for C", anchor: "CAXML00700", file: "xpath.htm" },
  { topic: "chapter", section: "14", title: "Package XPointer APIs for C", anchor: "CAXML01200", file: "xpointer.htm" },
  { topic: "chapter", section: "15", title: "Package XSLT APIs for C", anchor: "CAXML00800", file: "xslt.htm" },
  { topic: "chapter", section: "16", title: "Package XSLTVM APIs for C", anchor: "CAXML00900", file: "xsltvm.htm" },
  { topic: "appendix", section: "A", title: "Mapping of APIs used before Oracle Database 10g Release 1", anchor: "CAXML00010", file: "appendix.htm" },
  { } ];
