var chapters = [
  { topic: "chapter", section: "1", title: "Overview of Advanced Replication", anchor: "REPMA001", file: "raroverview.htm" },
  { topic: "chapter", section: "2", title: "Configuring the Replication Sites", anchor: "REPMA002", file: "rarrepsite.htm" },
  { topic: "chapter", section: "3", title: "Creating a Master Group", anchor: "REPMA003", file: "rarmastergroup.htm" },
  { topic: "chapter", section: "4", title: "Creating a Deployment Template", anchor: "REPMA004", file: "rardt.htm" },
  { topic: "chapter", section: "5", title: "Creating a Materialized View Group", anchor: "REPMA005", file: "rarmviewgroup.htm" },
  { topic: "chapter", section: "6", title: "Configuring Conflict Resolution", anchor: "REPMA006", file: "rarconflictres.htm" },
  { topic: "chapter", section: "7", title: "Managing a Master Replication Environment", anchor: "REPMA007", file: "rarmanmaster.htm" },
  { topic: "chapter", section: "8", title: "Managing a Materialized View Replication Environment", anchor: "REPMA008", file: "rarmanmv.htm" },
  { topic: "chapter", section: "9", title: "Managing Replication Objects and Queues", anchor: "REPMA009", file: "rarmanage.htm" },
  { topic: "chapter", section: "10", title: "Monitoring a Replication Environment", anchor: "REPMA030", file: "rarmonitor.htm" },
  { topic: "chapter", section: "11", title: "Introduction to the Replication Management API Reference", anchor: "REPMA010", file: "rarapi.htm" },
  { topic: "chapter", section: "12", title: "DBMS_DEFER", anchor: "REPMA011", file: "rardefpac.htm" },
  { topic: "chapter", section: "13", title: "DBMS_DEFER_QUERY", anchor: "REPMA012", file: "rardefquerypac.htm" },
  { topic: "chapter", section: "14", title: "DBMS_DEFER_SYS", anchor: "REPMA013", file: "rardefsyspac.htm" },
  { topic: "chapter", section: "15", title: "DBMS_OFFLINE_OG", anchor: "REPMA015", file: "raroffogpac.htm" },
  { topic: "chapter", section: "16", title: "DBMS_RECTIFIER_DIFF", anchor: "REPMA017", file: "rarrectdifpac.htm" },
  { topic: "chapter", section: "17", title: "DBMS_REFRESH", anchor: "REPMA018", file: "rarrefreshpac.htm" },
  { topic: "chapter", section: "18", title: "DBMS_REPCAT", anchor: "REPMA019", file: "rarrcatpac.htm" },
  { topic: "chapter", section: "19", title: "DBMS_REPCAT_INSTANTIATE", anchor: "REPMA021", file: "rarrcatinstantpac.htm" },
  { topic: "chapter", section: "20", title: "DBMS_REPCAT_ADMIN", anchor: "REPMA020", file: "rarrcatadminpac.htm" },
  { topic: "chapter", section: "21", title: "DBMS_REPCAT_RGT", anchor: "REPMA022", file: "rarrcatrgtpac.htm" },
  { topic: "chapter", section: "22", title: "DBMS_REPUTIL", anchor: "REPMA023", file: "rarreputilpac.htm" },
  { topic: "chapter", section: "23", title: "Replication Catalog Views", anchor: "REPMA024", file: "rarrcatviews.htm" },
  { topic: "chapter", section: "24", title: "Replication Dynamic Performance Views", anchor: "REPMA025", file: "rardynviews.htm" },
  { topic: "chapter", section: "25", title: "Materialized View and Refresh Group Views", anchor: "REPMA027", file: "rarsnapviews.htm" },
  { topic: "chapter", section: "26", title: "Deferred Transaction Views", anchor: "REPMA026", file: "rardeftranviews.htm" },
  { topic: "appendix", section: "A", title: "Security Options", anchor: "REPMA028", file: "rarsec.htm" },
  { topic: "appendix", section: "B", title: "User-Defined Conflict Resolution Methods", anchor: "REPMA029", file: "raruserconflictres.htm" },
  { } ];
