var chapters = [
  { topic: "chapter", section: "", title: " Introducing Oracle Database Real Application Security ", anchor: "DBFSG10000", file: "intro.htm" },
  { topic: "chapter", section: "", title: " Configuring Application Users and Application Roles ", anchor: "DBFSG20000", file: "users_roles.htm" },
  { topic: "chapter", section: "", title: " Configuring Application Sessions ", anchor: "DBFSG30000", file: "sessions.htm" },
  { topic: "chapter", section: "", title: " Configuring Application Privileges and Access Control Lists", anchor: "DBFSG99152", file: "acls_sec_classes.htm" },
  { topic: "chapter", section: "", title: " Configuring Data Security", anchor: "DBFSG4000", file: "data_security.htm" },
  { topic: "chapter", section: "", title: "Using Real Application Security in Java Applications ", anchor: "DBFSG99844", file: "midtierjava.htm" },
  { topic: "chapter", section: "", title: "Oracle Fusion Middleware Integration with Real Application Security ", anchor: "DBFSG507", file: "external_roles.htm" },
  { topic: "chapter", section: "", title: "Application Session Service in Oracle Fusion Middleware ", anchor: "DBFSG457", file: "session_service.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Real Application Security Data\u00A0Dictionary\u00A0Views ", anchor: "DBFSG60000", file: "parm_views.htm" },
  { topic: "chapter", section: "", title: " Oracle Database Real Application Security SQL\u00A0Functions ", anchor: "DBFSG70000", file: "plsql_fun.htm" },
  { topic: "chapter", section: "", title: " Oracle Database Real Application Security PL/SQL\u00A0Packages ", anchor: "DBFSG80000", file: "plsql_pkg.htm" },
  { topic: "chapter", section: "", title: "Real Application Security HR Demo ", anchor: "DBFSG806", file: "security_hr_demo_tutorial.htm" },
  { topic: "appendix", section: "", title: "Predefined Objects in Real Application Security ", anchor: "DBFSG291", file: "predefined_components.htm" },
  { topic: "appendix", section: "", title: " Configuring OCI and JDBC Applications for Column Authorization", anchor: "DBFSG12001", file: "oci_jdbc.htm" },
  { topic: "appendix", section: "", title: "Real Application Security HR Demo Files", anchor: "DBFSG819", file: "security_hr_demo_files.htm" },
  { topic: "appendix", section: "", title: " Troubleshooting Oracle Database Real Application Security", anchor: "DBFSG11000", file: "troubleshooting.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "DBFSG12000", file: "glossary.htm" },
  { } ];
