var chapters = [
  { topic: "chapter", section: "1", title: "Oracle Database Architecture on Windows", anchor: "NTQRF010", file: "architec.htm" },
  { topic: "chapter", section: "2", title: "Database Tools on Windows", anchor: "NTQRF040", file: "tools.htm" },
  { topic: "chapter", section: "3", title: "Supporting Oracle Home User on Windows", anchor: "NTQRF672", file: "oh_usr.htm" },
  { topic: "chapter", section: "4", title: "Postinstallation Database Creation on Windows", anchor: "NTQRF050", file: "create.htm" },
  { topic: "chapter", section: "5", title: "Postinstallation Configuration Tasks on Windows", anchor: "NTQRF060", file: "config.htm" },
  { topic: "chapter", section: "6", title: "Administering a Database on Windows", anchor: "NTQRF070", file: "admin.htm" },
  { topic: "chapter", section: "7", title: "Monitoring a Database on Windows", anchor: "NTQRF080", file: "monitor.htm" },
  { topic: "chapter", section: "8", title: "Tuning Windows to Optimize Oracle Database", anchor: "NTQRF090", file: "tuning.htm" },
  { topic: "chapter", section: "9", title: "Performing Database Backup and Recovery with VSS", anchor: "NTQRF280", file: "vss.htm" },
  { topic: "chapter", section: "10", title: "Authenticating Database Users with Windows", anchor: "NTQRF120", file: "authen.htm" },
  { topic: "chapter", section: "11", title: "Administering External Users and Roles on Windows", anchor: "NTQRF130", file: "external.htm" },
  { topic: "chapter", section: "12", title: "Storing Oracle Wallets in the Windows Registry", anchor: "NTQRF150", file: "wallets.htm" },
  { topic: "chapter", section: "13", title: "Oracle PKI Integration with Windows", anchor: "NTQRF160", file: "pki.htm" },
  { topic: "chapter", section: "14", title: "Using Oracle Database with Microsoft Active Directory", anchor: "NTQRF270", file: "active_dir.htm" },
  { topic: "chapter", section: "15", title: "Oracle Database Specifications for Windows", anchor: "NTQRF170", file: "specs.htm" },
  { topic: "chapter", section: "16", title: "Configuration Parameters and the Registry", anchor: "NTQRF180", file: "registry.htm" },
  { topic: "chapter", section: "17", title: "Developing Applications for Windows", anchor: "NTQRF190", file: "apps.htm" },
  { topic: "appendix", section: "A", title: "Storing Tablespaces on Raw Partitions", anchor: "NTQRF210", file: "ap_raw.htm" },
  { topic: "appendix", section: "B", title: "Oracle Net Services Configuration on Windows", anchor: "NTQRF220", file: "ap_net.htm" },
  { topic: "appendix", section: "C", title: "Running Windows Services", anchor: "NTQRF700", file: "ap_services.htm" },
  { topic: "appendix", section: "D", title: "Error Messages on Windows", anchor: "NTQRF230", file: "ap_error.htm" },
  { topic: "appendix", section: "E", title: "Oracle Database Differences on Windows and UNIX", anchor: "NTQRF250", file: "ap_unix.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "NTQRF546", file: "glossary.htm" },
  { } ];
