var chapters = [
  { topic: "chapter", section: "1", title: "Introducing Oracle Data Provider for .NET", anchor: "ODPNT0005", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Installing and Configuring<br />Oracle Data Provider for .NET", anchor: "ODPNT0006", file: "install.htm" },
  { topic: "chapter", section: "3", title: "Features of Oracle Data Provider for .NET", anchor: "ODPNT0007", file: "features.htm" },
  { topic: "chapter", section: "4", title: "ADO.NET Entity Framework and LINQ to Entities", anchor: "ODPNT8273", file: "entity_framework.htm" },
  { topic: "chapter", section: "5", title: "Oracle Data Provider for .NET Stored Procedures", anchor: "ODPNT0017", file: "extensions.htm" },
  { topic: "chapter", section: "6", title: "Oracle Data Provider for .NET Classes", anchor: "ODPNT0008", file: "client.htm" },
  { topic: "chapter", section: "7", title: "Oracle Data Provider for .NET<br /> XML-Related Classes", anchor: "ODPNT0010", file: "xmlclass.htm" },
  { topic: "chapter", section: "8", title: "Oracle Data Provider for .NET HA Event Classes", anchor: "ODPNT2861", file: "haevent.htm" },
  { topic: "chapter", section: "9", title: "Continuous Query Notification Classes", anchor: "ODPNT0011", file: "changenote.htm" },
  { topic: "chapter", section: "10", title: "Oracle Data Provider for .NET<br /> Globalization Classes", anchor: "ODPNT0012", file: "global.htm" },
  { topic: "chapter", section: "11", title: "Oracle Data Provider for .NET<br /> Failover Classes", anchor: "ODPNT0013", file: "failov.htm" },
  { topic: "chapter", section: "12", title: "Oracle Database Advanced Queuing Classes", anchor: "ODPNT3288", file: "aq.htm" },
  { topic: "chapter", section: "13", title: "Oracle Data Provider for .NET Types\u00A0Classes", anchor: "ODPNT0014", file: "typeobjs.htm" },
  { topic: "chapter", section: "14", title: "Oracle Data Provider for .NET<br /> Types Structures", anchor: "ODPNT0009", file: "oratypes.htm" },
  { topic: "chapter", section: "15", title: "Oracle Data Provider for .NET Types Exceptions", anchor: "ODPNT0015", file: "typeexcep.htm" },
  { topic: "chapter", section: "16", title: "Oracle Data Provider for .NET UDT-Related Classes", anchor: "ODPNT0022", file: "objects.htm" },
  { topic: "chapter", section: "17", title: "Oracle Data Provider for .NET <br />Bulk Copy Classes", anchor: "ODPNT0021", file: "bulkcopy.htm" },
  { topic: "appendix", section: "A", title: "Oracle Schema Collections", anchor: "ODPNT8028", file: "appendix.htm" },
  { topic: "appendix", section: "B", title: "Mapping LINQ Canonical Functions and Oracle Functions", anchor: "ODPNT8081", file: "canonical_map.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "ODPNT8088", file: "glossary.htm" },
  { } ];
