var chapters = [
  { topic: "chapter", section: "", title: "Introduction to SQL Tuning", anchor: "TGSQL112", file: "tgsql_intro.htm" },
  { topic: "chapter", section: "", title: "SQL Performance Methodology", anchor: "TGSQL133", file: "tgsql_method.htm" },
  { topic: "chapter", section: "", title: "SQL Processing ", anchor: "TGSQL175", file: "tgsql_sqlproc.htm" },
  { topic: "chapter", section: "", title: "Query Optimizer Concepts ", anchor: "TGSQL192", file: "tgsql_optcncpt.htm" },
  { topic: "chapter", section: "", title: "Query Transformations", anchor: "TGSQL94896", file: "tgsql_transform.htm" },
  { topic: "chapter", section: "", title: "Generating and Displaying Execution Plans ", anchor: "TGSQL271", file: "tgsql_genplan.htm" },
  { topic: "chapter", section: "", title: "Reading Execution Plans ", anchor: "TGSQL94618", file: "tgsql_interp.htm" },
  { topic: "chapter", section: "", title: "Optimizer Access Paths", anchor: "TGSQL228", file: "tgsql_optop.htm" },
  { topic: "chapter", section: "", title: "Joins", anchor: "TGSQL242", file: "tgsql_join.htm" },
  { topic: "chapter", section: "", title: "Optimizer Statistics Concepts", anchor: "TGSQL336", file: "tgsql_statscon.htm" },
  { topic: "chapter", section: "", title: "Histograms ", anchor: "TGSQL366", file: "tgsql_histo.htm" },
  { topic: "chapter", section: "", title: "Managing Optimizer Statistics: Basic Topics", anchor: "TGSQL389", file: "tgsql_stats.htm" },
  { topic: "chapter", section: "", title: "Managing Optimizer Statistics: Advanced Topics", anchor: "TGSQL449", file: "tgsql_astat.htm" },
  { topic: "chapter", section: "", title: "Influencing the Optimizer ", anchor: "TGSQL246", file: "tgsql_influence.htm" },
  { topic: "chapter", section: "", title: "Improving Real-World Performance Through Cursor Sharing", anchor: "TGSQL848", file: "tgsql_cursor.htm" },
  { topic: "chapter", section: "", title: "Monitoring Database Operations", anchor: "TGSQL789", file: "tgsql_monit.htm" },
  { topic: "chapter", section: "", title: "Gathering Diagnostic Data with SQL Test Case Builder", anchor: "TGSQL94840", file: "tgsql_stcb.htm" },
  { topic: "chapter", section: "", title: "Performing Application Tracing ", anchor: "TGSQL791", file: "tgsql_trace.htm" },
  { topic: "chapter", section: "", title: "Managing SQL Tuning Sets ", anchor: "TGSQL516", file: "tgsql_sts.htm" },
  { topic: "chapter", section: "", title: "Analyzing SQL with SQL Tuning Advisor ", anchor: "TGSQL540", file: "tgsql_sqltune.htm" },
  { topic: "chapter", section: "", title: "Optimizing Access Paths with SQL Access Advisor ", anchor: "TGSQL591", file: "tgsql_sqlaccess.htm" },
  { topic: "chapter", section: "", title: "Managing SQL Profiles ", anchor: "TGSQL596", file: "tgsql_profiles.htm" },
  { topic: "chapter", section: "", title: "Managing SQL Plan Baselines", anchor: "TGSQL94621", file: "tgsql_spm.htm" },
  { topic: "chapter", section: "", title: "Migrating Stored Outlines to SQL Plan Baselines ", anchor: "TGSQL665", file: "tgsql_mig.htm" },
  { topic: "appendix", section: "", title: "Guidelines for Indexes and Table Clusters", anchor: "TGSQL850", file: "tgsql_indc.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "TGSQL683", file: "glossary.htm" },
  { } ];
