var chapters = [
  { topic: "chapter", section: "", title: " OCI: Introduction and Upgrading", anchor: "LNOCI010", file: "oci01int.htm" },
  { topic: "chapter", section: "", title: " OCI Programming Basics", anchor: "LNOCI020", file: "oci02bas.htm" },
  { topic: "chapter", section: "", title: " Data Types", anchor: "LNOCI030", file: "oci03typ.htm" },
  { topic: "chapter", section: "", title: " Using SQL Statements in OCI", anchor: "LNOCI040", file: "oci04sql.htm" },
  { topic: "chapter", section: "", title: " Binding and Defining in OCI", anchor: "LNOCI050", file: "oci05bnd.htm" },
  { topic: "chapter", section: "", title: " Describing Schema Metadata", anchor: "LNOCI060", file: "oci06des.htm" },
  { topic: "chapter", section: "", title: " LOB and BFILE Operations", anchor: "LNOCI070", file: "oci07lob.htm" },
  { topic: "chapter", section: "", title: " Managing Scalable Platforms", anchor: "LNOCI080", file: "oci08sca.htm" },
  { topic: "chapter", section: "", title: "																					 OCI Programming Advanced Topics", anchor: "LNOCI090", file: "oci09adv.htm" },
  { topic: "chapter", section: "", title: "   More OCI Advanced Topics", anchor: "LNOCI092", file: "oci10new.htm" },
  { topic: "chapter", section: "", title: " OCI Object-Relational Programming ", anchor: "LNOCI100", file: "oci11obj.htm" },
  { topic: "chapter", section: "", title: " Object-Relational Data Types in OCI", anchor: "LNOCI110", file: "oci12oty.htm" },
  { topic: "chapter", section: "", title: " Direct Path Load Interface", anchor: "LNOCI120", file: "oci13obn.htm" },
  { topic: "chapter", section: "", title: "   Object Advanced Topics in OCI", anchor: "LNOCI130", file: "oci14oca.htm" },
  { topic: "chapter", section: "", title: " Using the Object Type Translator with OCI", anchor: "LNOCI140", file: "oci15ott.htm" },
  { topic: "chapter", section: "", title: " Oracle Database Access C API", anchor: "LNOCI150", file: "oci16rel.htm" },
  { topic: "chapter", section: "", title: " More Oracle Database Access C API", anchor: "LNOCI160", file: "oci17msc.htm" },
  { topic: "chapter", section: "", title: " OCI Navigational and Type Functions", anchor: "LNOCI170", file: "oci18nav.htm" },
  { topic: "chapter", section: "", title: " OCI Data Type Mapping and Manipulation Functions", anchor: "LNOCI180", file: "oci19map.htm" },
  { topic: "chapter", section: "", title: " OCI Cartridge Functions", anchor: "LNOCI190", file: "oci20ext.htm" },
  { topic: "chapter", section: "", title: " OCI Any Type and Data Functions", anchor: "LNOCI200", file: "oci21any.htm" },
  { topic: "chapter", section: "", title: " OCI Globalization Support Functions", anchor: "LNOCI210", file: "oci22glb.htm" },
  { topic: "chapter", section: "", title: " OCI XML DB Functions", anchor: "LNOCI220", file: "oci23xml.htm" },
  { topic: "chapter", section: "", title: "Oracle ODBC Driver ", anchor: "LNOCI72825", file: "oci24odbc.htm" },
  { topic: "chapter", section: "", title: "Introduction to the OCI Interface for XStream ", anchor: "LNOCI72903", file: "oci25xstrmint.htm" },
  { topic: "chapter", section: "", title: "OCI XStream Functions ", anchor: "LNOCI72914", file: "oci26strm.htm" },
  { topic: "appendix", section: "", title: "         Handle and Descriptor Attributes", anchor: "LNOCI250", file: "ociaahan.htm" },
  { topic: "appendix", section: "", title: "  OCI Demonstration Programs", anchor: "LNOCI280", file: "ociabdem.htm" },
  { topic: "appendix", section: "", title: " OCI Function Server Round-Trips", anchor: "LNOCI300", file: "ociacrou.htm" },
  { topic: "appendix", section: "", title: "  Getting Started with OCI for Windows", anchor: "LNOCI350", file: "ociadwin.htm" },
  { topic: "appendix", section: "", title: "Deprecated OCI Functions", anchor: "LNOCI72888", file: "ociaedep.htm" },
  { topic: "appendix", section: "", title: "Multithreaded extproc Agent", anchor: "LNOCI00099", file: "ociafextproc.htm" },
  { } ];
