var chapters = [
  { topic: "chapter", section: "", title: "Overview of PL/SQL", anchor: "LNPLS001", file: "overview.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Language Fundamentals", anchor: "LNPLS002", file: "fundamentals.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Data Types", anchor: "LNPLS003", file: "datatypes.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Control Statements", anchor: "LNPLS004", file: "controlstatements.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Collections and Records", anchor: "LNPLS005", file: "composites.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Static SQL", anchor: "LNPLS006", file: "static.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Dynamic SQL", anchor: "LNPLS011", file: "dynamic.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Subprograms", anchor: "LNPLS174", file: "subprograms.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Triggers", anchor: "LNPLS179", file: "triggers.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Packages", anchor: "LNPLS181", file: "packages.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Error Handling", anchor: "LNPLS007", file: "errors.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Optimization and Tuning", anchor: "LNPLS012", file: "tuning.htm" },
  { topic: "chapter", section: "", title: "PL/SQL Language Elements", anchor: "LNPLS013", file: "langelems.htm" },
  { topic: "chapter", section: "", title: "SQL Statements for Stored PL/SQL Units", anchor: "LNPLS99979", file: "sqlstatements.htm" },
  { topic: "appendix", section: "", title: "PL/SQL Source Text Wrapping", anchor: "LNPLS016", file: "wrap.htm" },
  { topic: "appendix", section: "", title: "PL/SQL Name Resolution", anchor: "LNPLS017", file: "nameresolution.htm" },
  { topic: "appendix", section: "", title: "PL/SQL Program Limits", anchor: "LNPLS018", file: "limits.htm" },
  { topic: "appendix", section: "", title: "PL/SQL Reserved Words and Keywords", anchor: "LNPLS019", file: "reservedwords.htm" },
  { topic: "appendix", section: "", title: "PL/SQL Predefined Data Types", anchor: "LNPLS2163", file: "predefined.htm" },
  { } ];
