var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle XML Developer's Kit", anchor: "ADXDK100", file: "adx_overview.htm" },
  { topic: "chapter", section: "2", title: "Unified Java API for XML", anchor: "ADXDK8880", file: "adx_j_uapi.htm" },
  { topic: "chapter", section: "3", title: "Getting Started with Oracle XML Developer's Kit for Java", anchor: "ADXDK2000", file: "adx_j_gs.htm" },
  { topic: "chapter", section: "4", title: "XML Parsing for Java", anchor: "ADXDK3000", file: "adx_j_parser.htm" },
  { topic: "chapter", section: "5", title: "Using Binary XML with Java", anchor: "ADXDK4440", file: "adx_j_xmlbin.htm" },
  { topic: "chapter", section: "6", title: "Using the XSLT Processor for Java", anchor: "ADXDK4000", file: "adx_j_xslt.htm" },
  { topic: "chapter", section: "7", title: "Using the XQuery Processor for Java", anchor: "ADXDK99930", file: "adx_j_xqj.htm" },
  { topic: "chapter", section: "8", title: "Using XQuery API for Java to Access Oracle XML DB", anchor: "ADXDK136", file: "adx_j_xqjxdb.htm" },
  { topic: "chapter", section: "9", title: "Using the XML Schema Processor for Java", anchor: "ADXDK5000", file: "adx_j_sproc.htm" },
  { topic: "chapter", section: "10", title: "Using the JAXB Class Generator", anchor: "ADXDK6000", file: "adx_j_jaxb.htm" },
  { topic: "chapter", section: "11", title: "Using the XML Pipeline Processor for Java", anchor: "ADXDK7000", file: "adx_j_pipeline.htm" },
  { topic: "chapter", section: "12", title: "Determining XML Differences Using Java", anchor: "ADXDK199", file: "adx_j_diff.htm" },
  { topic: "chapter", section: "13", title: "Using the XML SQL Utility", anchor: "ADXDK070", file: "adx_j_xsu.htm" },
  { topic: "chapter", section: "14", title: "Using the TransX Utility ", anchor: "ADXDK1200", file: "adx_j_transx.htm" },
  { topic: "chapter", section: "15", title: "Data Loading Format (DLF) Specification", anchor: "ADXDK19529", file: "adx_ref_dlf.htm" },
  { topic: "chapter", section: "16", title: "Using the XSQL Pages Publishing Framework", anchor: "ADXDK080", file: "adx_j_xsqlpub.htm" },
  { topic: "chapter", section: "17", title: "Using the XSQL Pages Publishing Framework: Advanced Topics", anchor: "ADXDK090", file: "adx_j_xsqladv.htm" },
  { topic: "chapter", section: "18", title: "Getting Started with Oracle XML Developer's Kit for C", anchor: "ADXDK1300", file: "adx_c_gs.htm" },
  { topic: "chapter", section: "19", title: "Using the XSLT and XVM Processors for C", anchor: "ADXDK1500", file: "adx_c_xslt.htm" },
  { topic: "chapter", section: "20", title: "Using the XML Parser for C", anchor: "ADXDK1400", file: "adx_c_parser.htm" },
  { topic: "chapter", section: "21", title: "Using Binary XML with C", anchor: "ADXDK1810", file: "adx_c_xmlbin.htm" },
  { topic: "chapter", section: "22", title: "Using the XML Schema Processor for C", anchor: "ADXDK1600", file: "adx_c_sproc.htm" },
  { topic: "chapter", section: "23", title: "Determining XML Differences Using C", anchor: "ADXDK2500", file: "adx_c_diff.htm" },
  { topic: "chapter", section: "24", title: "Using SOAP with the Oracle XML Developer's Kit for C", anchor: "ADXDK19852", file: "adx_c_soap.htm" },
  { topic: "chapter", section: "25", title: "Getting Started with Oracle XML Developer's Kit for C++", anchor: "ADXDK1700", file: "adx_cp_gs.htm" },
  { topic: "chapter", section: "26", title: "Overview of the Unified C++ Interfaces", anchor: "ADXDK1800", file: "adx_cp_unified.htm" },
  { topic: "chapter", section: "27", title: "Using the XML Parser for C++", anchor: "ADXDK1900", file: "adx_cp_parser.htm" },
  { topic: "chapter", section: "28", title: "Using the XSLT Processor for C++", anchor: "ADXDK2001", file: "adx_cp_xslt.htm" },
  { topic: "chapter", section: "29", title: "Using the XML Schema Processor for C++", anchor: "ADXDK2100", file: "adx_cp_sproc.htm" },
  { topic: "chapter", section: "30", title: "Using the XPath Processor for C++", anchor: "ADXDK2200", file: "adx_cp_xpath.htm" },
  { topic: "chapter", section: "31", title: "Using the XML Class Generator for C++ ", anchor: "ADXDK2300", file: "adx_cp_classgen.htm" },
  { topic: "chapter", section: "32", title: "XSQL Pages Reference", anchor: "ADXDK19952", file: "adx_ref_xsql.htm" },
  { topic: "chapter", section: "33", title: "Oracle XML Developer's Kit Standards", anchor: "ADXDK2400", file: "adx_ref_standards.htm" },
  { topic: "appendix", section: "A", title: "XDK for Java XML Error Messages", anchor: "ADXDK99936", file: "adx_ermg_xml.htm" },
  { topic: "appendix", section: "B", title: "XDK for Java TXU Error Messages", anchor: "ADXDK99947", file: "adx_ermg_txu.htm" },
  { topic: "appendix", section: "C", title: "XDK for Java XSU Error Messages", anchor: "ADXDK99954", file: "adx_ermg_xsu.htm" },
  { topic: "appendix", section: "D", title: "Oracle XML Developer's Kit JavaBeans (Deprecated)", anchor: "ADXDK223", file: "adx_j_beans_ap.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "ADXDK9000", file: "glossary.htm" },
  { } ];
