var chapters = [
  { topic: "chapter", section: "1", title: "Oracle Database Installation Checklist", anchor: "LADBI8045", file: "chklist.htm" },
  { topic: "chapter", section: "2", title: "Overview of Oracle Database Installation", anchor: "LADBI7430", file: "install_overview.htm" },
  { topic: "chapter", section: "3", title: "Automatically Configuring Oracle Linux with Oracle Preinstallation RPM", anchor: "LADBI7474", file: "olinrpm.htm" },
  { topic: "chapter", section: "4", title: "	Oracle Database Preinstallation Tasks", anchor: "LADBI222", file: "pre_install.htm" },
  { topic: "chapter", section: "5", title: "Configuring Users, Groups and Environments for Oracle Database", anchor: "LADBI7652", file: "usr_grps.htm" },
  { topic: "chapter", section: "6", title: "Oracle Grid Infrastructure for a Standalone Server", anchor: "LADBI999", file: "oraclerestart.htm" },
  { topic: "chapter", section: "7", title: "Installing Oracle Database", anchor: "LADBI7726", file: "inst_task.htm" },
  { topic: "chapter", section: "8", title: "Oracle Database Postinstallation Tasks", anchor: "LADBI7744", file: "post_inst_task.htm" },
  { topic: "chapter", section: "9", title: "Getting Started with Oracle Database", anchor: "LADBI006", file: "rev_precon_db.htm" },
  { topic: "chapter", section: "10", title: "Removing Oracle Database Software", anchor: "LADBI7824", file: "remove_oracle_sw.htm" },
  { topic: "appendix", section: "A", title: "Installing and Configuring Oracle Database Using Response Files", anchor: "LADBI7831", file: "app_nonint.htm" },
  { topic: "appendix", section: "B", title: "Cloning an Oracle Home", anchor: "LADBI7852", file: "app_cloning.htm" },
  { topic: "appendix", section: "C", title: "Using NAS Devices", anchor: "LADBI7855", file: "app_nas.htm" },
  { topic: "appendix", section: "D", title: "How to Complete Preinstallation Tasks Manually", anchor: "LADBI7864", file: "app_manual.htm" },
  { topic: "appendix", section: "E", title: "Configuring Networks for Oracle Database", anchor: "LADBI7891", file: "app_network.htm" },
  { topic: "appendix", section: "F", title: "Optimal Flexible Architecture", anchor: "LADBI0015", file: "appendix_ofa.htm" },
  { topic: "appendix", section: "G", title: "Managing Oracle Database Port Numbers", anchor: "LADBI7924", file: "app_port.htm" },
  { topic: "appendix", section: "H", title: "Configuring Oracle Database Globalization Support", anchor: "LADBI7932", file: "app_glblsupp.htm" },
  { topic: "appendix", section: "I", title: "Troubleshooting", anchor: "LADBI7939", file: "app_ts.htm" },
  { topic: "appendix", section: "J", title: "Frequently Asked Questions About Installation", anchor: "LADBI7957", file: "app_faq.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "LADBI7986", file: "glossary.htm" },
  { } ];
