var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Database Advanced Queuing", anchor: "ADQUE0100", file: "aq_intro.htm" },
  { topic: "chapter", section: "2", title: "Basic Components", anchor: "ADQUE0200", file: "componet.htm" },
  { topic: "chapter", section: "3", title: "Oracle Database Advanced Queuing: Programmatic Interfaces", anchor: "ADQUE0300", file: "aq_envir.htm" },
  { topic: "chapter", section: "4", title: "Managing Oracle Database Advanced Queuing", anchor: "ADQUE0400", file: "manage.htm" },
  { topic: "chapter", section: "5", title: "Oracle Database Advanced Queuing Performance and Scalability", anchor: "ADQUE0500", file: "perform.htm" },
  { topic: "chapter", section: "6", title: "Internet Access to Oracle Database Advanced Queuing", anchor: "ADQUE0600", file: "internet.htm" },
  { topic: "chapter", section: "7", title: "Troubleshooting Oracle Database Advanced Queuing", anchor: "ADQUE0700", file: "aq_trbl.htm" },
  { topic: "chapter", section: "8", title: "Oracle Database Advanced Queuing Administrative Interface", anchor: "ADQUE0800", file: "aq_admin.htm" },
  { topic: "chapter", section: "9", title: "Oracle Database Advanced Queuing and Messaging Gateway Views", anchor: "ADQUE0900", file: "aq_views.htm" },
  { topic: "chapter", section: "10", title: "Oracle Database Advanced Queuing Operations Using PL/SQL", anchor: "ADQUE1000", file: "aq_opers.htm" },
  { topic: "chapter", section: "11", title: "Introduction to Oracle Java Message Service", anchor: "ADQUE1100", file: "jm_create.htm" },
  { topic: "chapter", section: "12", title: "Oracle Java Message Service Basic Operations", anchor: "ADQUE1200", file: "jm_opers.htm" },
  { topic: "chapter", section: "13", title: "Oracle Java Message Service Point-to-Point", anchor: "ADQUE1300", file: "jm_point.htm" },
  { topic: "chapter", section: "14", title: "Oracle Java Message Service Publish/Subscribe", anchor: "ADQUE1400", file: "jm_pblsh.htm" },
  { topic: "chapter", section: "15", title: "Oracle Java Message Service Shared Interfaces", anchor: "ADQUE1500", file: "jm_share.htm" },
  { topic: "chapter", section: "16", title: "Oracle Java Message Service Types Examples", anchor: "ADQUE1600", file: "jm_exmpl.htm" },
  { topic: "chapter", section: "17", title: "Introduction to Oracle Messaging Gateway", anchor: "ADQUE1700", file: "mg_intro.htm" },
  { topic: "chapter", section: "18", title: "Getting Started with Oracle Messaging Gateway", anchor: "ADQUE1800", file: "mg_start.htm" },
  { topic: "chapter", section: "19", title: "Working with Oracle Messaging Gateway", anchor: "ADQUE1900", file: "mg_work.htm" },
  { topic: "chapter", section: "20", title: "Oracle Messaging Gateway Message Conversion", anchor: "ADQUE2000", file: "mg_trnsfm.htm" },
  { topic: "chapter", section: "21", title: "Monitoring Oracle Messaging Gateway", anchor: "ADQUE2100", file: "mg_trble.htm" },
  { topic: "chapter", section: "22", title: "Using ANYDATA Queues for User Messages", anchor: "ADQUE2200", file: "aq_stage.htm" },
  { topic: "chapter", section: "23", title: "Oracle Streams Messaging Examples", anchor: "ADQUE025", file: "aq_demo.htm" },
  { topic: "appendix", section: "A", title: "Nonpersistent Queues", anchor: "ADQUE2400", file: "ap_nonpers.htm" },
  { topic: "appendix", section: "B", title: "Oracle JMS and Oracle AQ XML Servlet Error Messages", anchor: "ADQUE3620", file: "aperrors.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "ADQUE3527", file: "glossary.htm" },
  { } ];
