var chapters = [
  { topic: "chapter", section: "1", title: " Introduction to Oracle Data Guard", anchor: "SBYDB00010", file: "concepts.htm" },
  { topic: "chapter", section: "2", title: " Getting Started with Oracle Data Guard", anchor: "SBYDB00100", file: "standby.htm" },
  { topic: "chapter", section: "3", title: " Creating a Physical Standby Database ", anchor: "SBYDB00200", file: "create_ps.htm" },
  { topic: "chapter", section: "4", title: " Creating a Logical Standby Database ", anchor: "SBYDB00300", file: "create_ls.htm" },
  { topic: "chapter", section: "5", title: "Far Sync ", anchor: "SBYDB5416", file: "create_fs.htm" },
  { topic: "chapter", section: "6", title: " Oracle Data Guard Protection Modes ", anchor: "SBYDB02000", file: "protection.htm" },
  { topic: "chapter", section: "7", title: " Redo Transport Services", anchor: "SBYDB00400", file: "log_transport.htm" },
  { topic: "chapter", section: "8", title: " Apply Services", anchor: "SBYDB00500", file: "log_apply.htm" },
  { topic: "chapter", section: "9", title: " Role Transitions", anchor: "SBYDB00600", file: "role_management.htm" },
  { topic: "chapter", section: "10", title: " Managing Physical and Snapshot Standby Databases", anchor: "SBYDB00700", file: "manage_ps.htm" },
  { topic: "chapter", section: "11", title: " Managing a Logical Standby Database", anchor: "SBYDB00800", file: "manage_ls.htm" },
  { topic: "chapter", section: "12", title: " Using RMAN to Back Up and Restore Files", anchor: "SBYDB04700", file: "rman.htm" },
  { topic: "chapter", section: "13", title: " Using SQL Apply to Upgrade the Oracle Database", anchor: "SBYDB00830", file: "rollup.htm" },
  { topic: "chapter", section: "14", title: "Using DBMS_ROLLING to Perform a Rolling Upgrade ", anchor: "SBYDB5214", file: "dbms_rolling_upgrades.htm" },
  { topic: "chapter", section: "15", title: " Oracle Data Guard Scenarios", anchor: "SBYDB00900", file: "scenarios.htm" },
  { topic: "chapter", section: "16", title: " Initialization Parameters", anchor: "SBYDB4901", file: "init_params.htm" },
  { topic: "chapter", section: "17", title: " LOG_ARCHIVE_DEST_n Parameter Attributes", anchor: "SBYDB01100", file: "log_arch_dest_param.htm" },
  { topic: "chapter", section: "18", title: " SQL Statements Relevant to Oracle Data Guard", anchor: "SBYDB01222", file: "sql_stmts.htm" },
  { topic: "chapter", section: "19", title: " Views Relevant to Oracle Data Guard ", anchor: "SBYDB01300", file: "views.htm" },
  { topic: "appendix", section: "A", title: " Troubleshooting Oracle Data Guard", anchor: "SBYDB01400", file: "troubleshooting.htm" },
  { topic: "appendix", section: "B", title: " Upgrading and Downgrading Databases in an Oracle Data Guard Configuration", anchor: "SBYDB1200", file: "upgrades.htm" },
  { topic: "appendix", section: "C", title: " Data Type and DDL Support on a Logical Standby Database ", anchor: "SBYDB00305", file: "data_support.htm" },
  { topic: "appendix", section: "D", title: " Oracle Data Guard and Oracle Real Application Clusters", anchor: "SBYDB01700", file: "rac_support.htm" },
  { topic: "appendix", section: "E", title: " Creating a Standby Database with Recovery Manager", anchor: "SBYDB01500", file: "rcmbackp.htm" },
  { topic: "appendix", section: "F", title: " Setting Archive Tracing", anchor: "SBYDB01880", file: "trace.htm" },
  { topic: "appendix", section: "G", title: "Performing Role Transitions Using Old Syntax", anchor: "SBYDB5172", file: "pre12_role_trans.htm" },
  { } ];
