var chapters = [
  { topic: "chapter", section: "1", title: "Overview of the Oracle Database Gateway Installation", anchor: "OTGIS100", file: "newoverview.htm" },
  { topic: "chapter", section: "2", title: "Installing Oracle Database Gateway for Sybase", anchor: "OTGIS200", file: "installsybase.htm" },
  { topic: "chapter", section: "3", title: "Configuring Oracle Database Gateway for Sybase", anchor: "OTGIS300", file: "configsybase.htm" },
  { topic: "chapter", section: "4", title: "Installing Oracle Database Gateway for Informix", anchor: "OTGIS400", file: "installinformix.htm" },
  { topic: "chapter", section: "5", title: "Configuring Oracle Database Gateway for Informix", anchor: "OTGIS500", file: "configinformix.htm" },
  { topic: "chapter", section: "6", title: "Installing Oracle Database Gateway for Teradata", anchor: "OTGIS600", file: "installteradata.htm" },
  { topic: "chapter", section: "7", title: "Configuring Oracle Database Gateway for Teradata", anchor: "OTGIS700", file: "configteradata.htm" },
  { topic: "chapter", section: "8", title: "Installing Oracle Database Gateway for SQL Server", anchor: "OTGIS800", file: "installsql.htm" },
  { topic: "chapter", section: "9", title: "Configuring Oracle Database Gateway for SQL Server", anchor: "OTGIS900", file: "configsql.htm" },
  { topic: "chapter", section: "10", title: "Installing Oracle Database Gateway for ODBC", anchor: "OTGIS230", file: "installodbc.htm" },
  { topic: "chapter", section: "11", title: "Configuring Oracle Database Gateway for ODBC", anchor: "OTGIS110", file: "configodbc.htm" },
  { topic: "chapter", section: "12", title: "Installing Oracle Database Gateway for DRDA", anchor: "OTGIS120", file: "installdrda.htm" },
  { topic: "chapter", section: "13", title: "Configuring the DRDA Server", anchor: "OTGIS130", file: "configdrda_server.htm" },
  { topic: "chapter", section: "14", title: "Configuring Oracle Database Gateway for DRDA", anchor: "OTGIS140", file: "configdrda_gtwy.htm" },
  { topic: "chapter", section: "15", title: "Security Considerations", anchor: "OTGIS150", file: "security.htm" },
  { topic: "chapter", section: "16", title: "Migration From Previous Releases", anchor: "OTGIS160", file: "migrate.htm" },
  { topic: "chapter", section: "17", title: "Removing Oracle Database Gateway", anchor: "OTGIS1245", file: "uninstall.htm" },
  { topic: "appendix", section: "A", title: "Using Response Files for Noninteractive Installation", anchor: "OTGIS180", file: "app_nonint.htm" },
  { topic: "appendix", section: "B", title: "Oracle Database Gateway Troubleshooting", anchor: "OTGIS190", file: "app_ts.htm" },
  { topic: "appendix", section: "C", title: "Initialization Parameters", anchor: "OTGIS240", file: "app_initparam.htm" },
  { topic: "appendix", section: "D", title: "Configuration Worksheet for DRDA", anchor: "OTGIS210", file: "app_wrksht.htm" },
  { } ];
