var chapters = [
  { topic: "chapter", section: "1", title: " Spatial Concepts", anchor: "SPATL010", file: "spatial-concepts.htm" },
  { topic: "chapter", section: "2", title: " Spatial Data Types and Metadata", anchor: "SPATL020", file: "spatial-data-types-and-metadata.htm" },
  { topic: "chapter", section: "3", title: " SQL Multimedia Type Support ", anchor: "SPATL025", file: "sql-multimedia-type-support.htm" },
  { topic: "chapter", section: "4", title: " Loading Spatial Data", anchor: "SPATL030", file: "loading-spatial-data.htm" },
  { topic: "chapter", section: "5", title: " Indexing and Querying Spatial Data", anchor: "SPATL040", file: "indexing-and-querying-spatial-data.htm" },
  { topic: "chapter", section: "6", title: " Coordinate Systems (Spatial Reference Systems)", anchor: "SPATL050", file: "coordinate-systems-spatial-reference-systems.htm" },
  { topic: "chapter", section: "7", title: " Linear Referencing System", anchor: "SPATL060", file: "linear-referencing-system.htm" },
  { topic: "chapter", section: "8", title: " Spatial Analysis and Mining", anchor: "SPATL070", file: "spatial-analysis-and-mining.htm" },
  { topic: "chapter", section: "9", title: " Extending Spatial Indexing Capabilities", anchor: "SPATL080", file: "extending-spatial-indexing-capabilities.htm" },
  { topic: "chapter", section: "10", title: " Introduction to Spatial Web Services", anchor: "SPATL044", file: "introduction-spatial-web-services.htm" },
  { topic: "chapter", section: "11", title: " Geocoding Address Data", anchor: "SPATL045", file: "geocoding-address-data.htm" },
  { topic: "chapter", section: "12", title: " Business Directory (Yellow Pages) Support", anchor: "SPATL400", file: "business-directory-yellow-pages-support.htm" },
  { topic: "chapter", section: "13", title: " Routing Engine", anchor: "SPATL350", file: "routing-engine.htm" },
  { topic: "chapter", section: "14", title: " OpenLS Support", anchor: "SPATL410", file: "openls-support.htm" },
  { topic: "chapter", section: "15", title: " Web Feature Service (WFS) Support", anchor: "SPATL420", file: "web-feature-service-wfs-support.htm" },
  { topic: "chapter", section: "16", title: " Catalog Services for the Web (CSW) Support", anchor: "SPATL425", file: "catalog-services-web-csw-support.htm" },
  { topic: "chapter", section: "17", title: " SQL Statements for Indexing Spatial Data", anchor: "SPATL090", file: "sql-statements-indexing-spatial-data.htm" },
  { topic: "chapter", section: "18", title: " Spatial Operators ", anchor: "SPATL110", file: "spatial-operators.htm" },
  { topic: "chapter", section: "19", title: " Spatial Aggregate Functions", anchor: "SPATL130", file: "spatial-aggregate-functions1.htm" },
  { topic: "chapter", section: "20", title: " SDO_CS Package (Coordinate System Transformation) ", anchor: "SPATL140", file: "sdo_cs-package-coordinate-system-transformation.htm" },
  { topic: "chapter", section: "21", title: " SDO_CSW_PROCESS Package (CSW Processing) ", anchor: "SPATL142", file: "sdo_csw_process-package-deprecated.htm" },
  { topic: "chapter", section: "22", title: " SDO_GCDR Package (Geocoding) ", anchor: "SPATL145", file: "sdo_gcdr-package-geocoding.htm" },
  { topic: "chapter", section: "23", title: " SDO_GEOM Package (Geometry)", anchor: "SPATL120", file: "sdo_geom-package-geometry.htm" },
  { topic: "chapter", section: "24", title: " SDO_LRS Package (Linear Referencing System) ", anchor: "SPATL150", file: "sdo_lrs-package-linear-referencing-system.htm" },
  { topic: "chapter", section: "25", title: " SDO_MIGRATE Package (Upgrading) ", anchor: "SPATL160", file: "sdo_migrate-package-upgrading.htm" },
  { topic: "chapter", section: "26", title: " SDO_OLS Package (OpenLS) ", anchor: "SPATL146", file: "sdo_ols-package-openls.htm" },
  { topic: "chapter", section: "27", title: " SDO_PC_PKG Package (Point Clouds)", anchor: "SPATL172", file: "sdo_pc_pkg-package-point-clouds.htm" },
  { topic: "chapter", section: "28", title: " SDO_SAM Package (Spatial Analysis and Mining)", anchor: "SPATL190", file: "sdo_sam-package-spatial-analysis-and-mining.htm" },
  { topic: "chapter", section: "29", title: " SDO_TIN_PKG Package (TINs)", anchor: "SPATL171", file: "sdo_tin_pkg-package-tins.htm" },
  { topic: "chapter", section: "30", title: " SDO_TUNE Package (Tuning)", anchor: "SPATL170", file: "sdo_tune-package-tuning.htm" },
  { topic: "chapter", section: "31", title: " SDO_UTIL Package (Utility)", anchor: "SPATL180", file: "sdo_util-package-utility.htm" },
  { topic: "chapter", section: "32", title: " SDO_WFS_LOCK Package (WFS) ", anchor: "SPATL147", file: "sdo_wfs_lock-package-wfs.htm" },
  { topic: "chapter", section: "33", title: " SDO_WFS_PROCESS Package (WFS Processing) ", anchor: "SPATL148", file: "sdo_wfs_process-package-wfs-processing.htm" },
  { topic: "appendix", section: "A", title: " Installation, Migration, Compatibility, and Upgrade", anchor: "SPATL320", file: "installation-migration-compatibility-and-upgrade.htm" },
  { topic: "appendix", section: "B", title: " Oracle Locator", anchor: "SPATL340", file: "sdo_locator.htm" },
  { topic: "appendix", section: "C", title: " Complex Spatial Queries: Examples", anchor: "SPATL1277", file: "complex-spatial-queries-examples.htm" },
  { topic: "appendix", section: "D", title: "Loading ESRI Shapefiles into Spatial and Graph", anchor: "SPATL1427", file: "loading-esri-shapefiles-spatial-and-graph.htm" },
  { topic: "appendix", section: "E", title: "Routing Engine Administration", anchor: "SPATL1561", file: "routing-engine-administration.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "SPATL1287", file: "glossary.htm" },
  { } ];
