var chapters = [
  { topic: "chapter", section: "1", title: " Oracle Text SQL Statements and Operators ", anchor: "CCREF0100", file: "csql.htm" },
  { topic: "chapter", section: "2", title: " Oracle Text Indexing Elements", anchor: "CCREF0200", file: "cdatadic.htm" },
  { topic: "chapter", section: "3", title: " Oracle Text CONTAINS Query Operators ", anchor: "CCREF0300", file: "cqoper.htm" },
  { topic: "chapter", section: "4", title: "Special Characters in Oracle Text Queries", anchor: "CCREF0400", file: "cqspcl.htm" },
  { topic: "chapter", section: "5", title: " CTX_ADM Package ", anchor: "CCREF0500", file: "cadmpkg.htm" },
  { topic: "chapter", section: "6", title: " CTX_ANL Package ", anchor: "CCREF24089", file: "canlpkg.htm" },
  { topic: "chapter", section: "7", title: " CTX_CLS Package ", anchor: "CCREF1500", file: "cclspkg.htm" },
  { topic: "chapter", section: "8", title: " CTX_DDL Package", anchor: "CCREF0600", file: "cddlpkg.htm" },
  { topic: "chapter", section: "9", title: " CTX_DOC Package ", anchor: "CCREF0700", file: "cdocpkg.htm" },
  { topic: "chapter", section: "10", title: " CTX_ENTITY Package ", anchor: "CCREF9753", file: "centit.htm" },
  { topic: "chapter", section: "11", title: " CTX_OUTPUT Package", anchor: "CCREF0800", file: "coutpkg.htm" },
  { topic: "chapter", section: "12", title: " CTX_QUERY Package", anchor: "CCREF2138", file: "cqrypkg.htm" },
  { topic: "chapter", section: "13", title: " CTX_REPORT Package ", anchor: "CCREF1100", file: "crptpkg.htm" },
  { topic: "chapter", section: "14", title: " CTX_THES Package ", anchor: "CCREF1600", file: "cthes.htm" },
  { topic: "chapter", section: "15", title: " CTX_ULEXER Package", anchor: "CCREF1700", file: "culexpkg.htm" },
  { topic: "chapter", section: "16", title: " Oracle Text Utilities ", anchor: "CCREF2180", file: "cexec.htm" },
  { topic: "chapter", section: "17", title: " Oracle Text Alternative Spelling", anchor: "CCREF1450", file: "cspell.htm" },
  { topic: "appendix", section: "A", title: " Oracle Text Result Tables", anchor: "CCREF1250", file: "arestab.htm" },
  { topic: "appendix", section: "B", title: " Oracle Text Supported Document Formats", anchor: "CCREF1300", file: "afilsupt.htm" },
  { topic: "appendix", section: "C", title: " Text Loading Examples for Oracle Text", anchor: "CCREF2257", file: "aload.htm" },
  { topic: "appendix", section: "D", title: " Oracle Text Multilingual Features", anchor: "CCREF1350", file: "amultlng.htm" },
  { topic: "appendix", section: "E", title: " Oracle Text Supplied Stoplists", anchor: "CCREF1400", file: "astopsup.htm" },
  { topic: "appendix", section: "F", title: " The Oracle Text Scoring Algorithm ", anchor: "CCREF1475", file: "ascore.htm" },
  { topic: "appendix", section: "G", title: " Oracle Text Views ", anchor: "CCREF1800", file: "aviews.htm" },
  { topic: "appendix", section: "H", title: " Stopword Transformations in Oracle Text", anchor: "CCREF1900", file: "astoptrn.htm" },
  { } ];
