var chapters = [
  { topic: "chapter", section: "1", title: " Introduction to Oracle XML\u00A0DB", anchor: "ADXDB0100", file: "xdb01int.htm" },
  { topic: "chapter", section: "2", title: " Getting Started with Oracle XML\u00A0DB", anchor: "ADXDB0200", file: "xdb02rep.htm" },
  { topic: "chapter", section: "3", title: " Overview of How To Use Oracle XML\u00A0DB", anchor: "ADXDB0300", file: "xdb03usg.htm" },
  { topic: "chapter", section: "4", title: "XQuery and Oracle XML\u00A0DB", anchor: "ADXDB1700", file: "xdb_xquery.htm" },
  { topic: "chapter", section: "5", title: " Query and Update of XML Data", anchor: "ADXDB0400", file: "xdb04cre.htm" },
  { topic: "chapter", section: "6", title: "Indexes for XMLType Data", anchor: "ADXDB0500", file: "xdb_indexing.htm" },
  { topic: "chapter", section: "7", title: " Transformation and Validation of XMLType Data", anchor: "ADXDB0900", file: "xdb08tra.htm" },
  { topic: "chapter", section: "8", title: " Generation of XML Data from Relational Data", anchor: "ADXDB1600", file: "xdb13gen.htm" },
  { topic: "chapter", section: "9", title: "Relational Views over XML Data", anchor: "ADXDB6124", file: "xdb_rel_views.htm" },
  { topic: "chapter", section: "10", title: " XMLType Views", anchor: "ADXDB1800", file: "xdb14vie.htm" },
  { topic: "chapter", section: "11", title: " PL/SQL APIs for XMLType", anchor: "ADXDB1100", file: "xdb10pls.htm" },
  { topic: "chapter", section: "12", title: " PL/SQL Package DBMS_XMLSTORE", anchor: "ADXDB1200", file: "xdb_dbmstore.htm" },
  { topic: "chapter", section: "13", title: " Java DOM API for XMLType", anchor: "ADXDB1300", file: "xdb11jav.htm" },
  { topic: "chapter", section: "14", title: " The C API for XML", anchor: "ADXDB1400", file: "xdb12oci.htm" },
  { topic: "chapter", section: "15", title: " Oracle XML\u00A0DB and Oracle Data Provider for .NET ", anchor: "ADXDB1500", file: "xdb_odpnet.htm" },
  { topic: "chapter", section: "16", title: "Choice of XMLType Storage and Indexing", anchor: "ADXDB6348", file: "xdb_storage.htm" },
  { topic: "chapter", section: "17", title: "XML Schema Storage and Query: Basic", anchor: "ADXDB0600", file: "xdb05sto.htm" },
  { topic: "chapter", section: "18", title: " XML Schema Storage and Query: Object-Relational Storage", anchor: "ADXDB0700", file: "xdb06stt.htm" },
  { topic: "chapter", section: "19", title: " XPath Rewrite for Object-Relational Storage", anchor: "ADXDB0670", file: "xdb_rewrite.htm" },
  { topic: "chapter", section: "20", title: " XML Schema Evolution", anchor: "ADXDB0800", file: "xdb07evo.htm" },
  { topic: "chapter", section: "21", title: " Access to Oracle XML\u00A0DB Repository Data", anchor: "ADXDB2000", file: "xdb16fol.htm" },
  { topic: "chapter", section: "22", title: " Configuration of Oracle XML\u00A0DB Repository", anchor: "ADXDB2050", file: "xdb_repos_config.htm" },
  { topic: "chapter", section: "23", title: " Use of XLink and XInclude with Oracle XML\u00A0DB", anchor: "ADXDB3800", file: "xdb_xlink.htm" },
  { topic: "chapter", section: "24", title: " Repository Access Using RESOURCE_VIEW and PATH_VIEW ", anchor: "ADXDB2200", file: "xdb18res.htm" },
  { topic: "chapter", section: "25", title: " Resource Versions", anchor: "ADXDB2100", file: "xdb17ver.htm" },
  { topic: "chapter", section: "26", title: " PL/SQL Access to Oracle XML\u00A0DB Repository ", anchor: "ADXDB2300", file: "xdb19rpl.htm" },
  { topic: "chapter", section: "27", title: " Repository Access Control", anchor: "ADXDB2400", file: "xdb21sec.htm" },
  { topic: "chapter", section: "28", title: " Repository Access Using Protocols", anchor: "ADXDB2500", file: "xdb22pro.htm" },
  { topic: "chapter", section: "29", title: " User-Defined Repository Metadata", anchor: "ADXDB2560", file: "xdb_repos_meta.htm" },
  { topic: "chapter", section: "30", title: " Oracle XML\u00A0DB Repository Events", anchor: "ADXDB2580", file: "xdb_repos_events.htm" },
  { topic: "chapter", section: "31", title: " Oracle XML DB Content Connector", anchor: "ADXDB2630", file: "xdb_jcr.htm" },
  { topic: "chapter", section: "32", title: " Guidelines for Oracle XML\u00A0DB Applications in Java", anchor: "ADXDB2600", file: "xdb23jv1.htm" },
  { topic: "chapter", section: "33", title: " Data Access Using URIs", anchor: "ADXDB1900", file: "xdb15dbu.htm" },
  { topic: "chapter", section: "34", title: "Native Oracle XML\u00A0DB Web Services ", anchor: "ADXDB3900", file: "xdb_web_services.htm" },
  { topic: "chapter", section: "35", title: " Administration of Oracle XML\u00A0DB", anchor: "ADXDB2700", file: "appaman.htm" },
  { topic: "chapter", section: "36", title: " How to Load XML Data", anchor: "ADXDB2900", file: "xdb25loa.htm" },
  { topic: "chapter", section: "37", title: " Export and Import of Oracle XML\u00A0DB Data", anchor: "ADXDB3000", file: "xdb26imp.htm" },
  { topic: "chapter", section: "38", title: " XML Data Exchange Using Oracle Streams\u00A0AQ", anchor: "ADXDB3100", file: "xdb27aq.htm" },
  { topic: "chapter", section: "39", title: "JSON in Oracle Database", anchor: "ADXDB6246", file: "json.htm" },
  { topic: "appendix", section: "A", title: " Oracle-Supplied XML Schemas and Examples", anchor: "ADXDB3600", file: "apphxdb.htm" },
  { topic: "appendix", section: "B", title: " Oracle XML\u00A0DB Restrictions", anchor: "ADXDB3700", file: "appjspec.htm" },
  { topic: "appendix", section: "C", title: "Deprecated Functions for Updating XML Data", anchor: "ADXDB6044", file: "app_depr_upd.htm" },
  { topic: "appendix", section: "D", title: "Deprecated Constructs for XML Translation", anchor: "ADXDB6130", file: "app_depr_transl.htm" },
  { topic: "appendix", section: "E", title: "Full-Text Search over XML Data Without XQuery", anchor: "ADXDB1000", file: "app_depr_otext.htm" },
  { } ];
