var chapters = [
  { topic: "chapter", section: "1", title: "Introducing JDBC", anchor: "JJDBC28025", file: "overvw.htm" },
  { topic: "chapter", section: "2", title: "Getting Started", anchor: "JJDBC20000", file: "getsta.htm" },
  { topic: "chapter", section: "3", title: "JDBC Standards Support", anchor: "JJDBC28082", file: "jdbcvers.htm" },
  { topic: "chapter", section: "4", title: "Oracle Extensions", anchor: "JJDBC28120", file: "oraint.htm" },
  { topic: "chapter", section: "5", title: "Features Specific to JDBC Thin", anchor: "JJDBC28195", file: "jdbcthin.htm" },
  { topic: "chapter", section: "6", title: "Features Specific to JDBC OCI Driver", anchor: "JJDBC28217", file: "instclnt.htm" },
  { topic: "chapter", section: "7", title: "Server-Side Internal Driver", anchor: "JJDBC28250", file: "ssid.htm" },
  { topic: "chapter", section: "8", title: "Data Sources and URLs", anchor: "JJDBC28267", file: "urls.htm" },
  { topic: "chapter", section: "9", title: "JDBC Client-Side Security Features", anchor: "JJDBC28295", file: "clntsec.htm" },
  { topic: "chapter", section: "10", title: "Proxy Authentication", anchor: "JJDBC28352", file: "proxya.htm" },
  { topic: "chapter", section: "11", title: "Accessing and Manipulating Oracle Data", anchor: "JJDBC28363", file: "datacc.htm" },
  { topic: "chapter", section: "12", title: "Java Streams in JDBC", anchor: "JJDBC28409", file: "jstreams.htm" },
  { topic: "chapter", section: "13", title: "Working with Oracle Object Types", anchor: "JJDBC28431", file: "oraoot.htm" },
  { topic: "chapter", section: "14", title: "Working with LOBs and BFILEs", anchor: "JJDBC15000", file: "oralob.htm" },
  { topic: "chapter", section: "15", title: "Using Oracle Object References", anchor: "JJDBC28566", file: "oraoor.htm" },
  { topic: "chapter", section: "16", title: "Working with Oracle Collections", anchor: "JJDBC28574", file: "oraarr.htm" },
  { topic: "chapter", section: "17", title: "Result Set", anchor: "JJDBC28611", file: "resltset.htm" },
  { topic: "chapter", section: "18", title: "JDBC RowSets", anchor: "JJDBC28630", file: "jcrowset.htm" },
  { topic: "chapter", section: "19", title: "Globalization Support", anchor: "JJDBC28643", file: "global.htm" },
  { topic: "chapter", section: "20", title: "Statement and Result Set Caching", anchor: "JJDBC28649", file: "stmtcach.htm" },
  { topic: "chapter", section: "21", title: "Performance Extensions", anchor: "JJDBC28752", file: "oraperf.htm" },
  { topic: "chapter", section: "22", title: "OCI Connection Pooling", anchor: "JJDBC28789", file: "ociconpl.htm" },
  { topic: "chapter", section: "23", title: "Database Resident Connection Pooling", anchor: "JJDBC29023", file: "drcp.htm" },
  { topic: "chapter", section: "24", title: "Oracle Advanced Queuing", anchor: "JJDBC28801", file: "streamsaq.htm" },
  { topic: "chapter", section: "25", title: "Continuous Query Notification", anchor: "JJDBC28815", file: "dbchgnf.htm" },
  { topic: "chapter", section: "26", title: "Transaction Guard for Java", anchor: "JJDBC29121", file: "transactionguard.htm" },
  { topic: "chapter", section: "27", title: "Application Continuity for Java", anchor: "JJDBC29059", file: "appcontnew.htm" },
  { topic: "chapter", section: "28", title: "Transparent Application Failover", anchor: "JJDBC27000", file: "ocitaf.htm" },
  { topic: "chapter", section: "29", title: "Single Client Access Name", anchor: "JJDBC29151", file: "scan.htm" },
  { topic: "chapter", section: "30", title: "Distributed Transactions", anchor: "JJDBC28000", file: "xadistra.htm" },
  { topic: "chapter", section: "31", title: "Database Administration", anchor: "JJDBC28880", file: "dbmgmnt.htm" },
  { topic: "chapter", section: "32", title: "Diagnosability in JDBC", anchor: "JJDBC28885", file: "diagnose.htm" },
  { topic: "chapter", section: "33", title: "JDBC DMS Metrics", anchor: "JJDBC28899", file: "dmsmtrc.htm" },
  { topic: "appendix", section: "A", title: "JDBC Reference Information", anchor: "JJDBC28905", file: "apxref.htm" },
  { topic: "appendix", section: "B", title: "Oracle RAC Fast Application Notification", anchor: "JJDBC28934", file: "apxracfan.htm" },
  { topic: "appendix", section: "C", title: "JDBC Coding Tips", anchor: "JJDBC28948", file: "apxtips.htm" },
  { topic: "appendix", section: "D", title: "JDBC Error Messages", anchor: "JJDBC28959", file: "apxermsg.htm" },
  { topic: "appendix", section: "E", title: "Troubleshooting", anchor: "JJDBC28976", file: "apxtblsh.htm" },
  { } ];
