var chapters = [
  { topic: "chapter", section: "1", title: "Preparing for Oracle Streams Replication", anchor: "STREP011", file: "prep_rep.htm" },
  { topic: "chapter", section: "2", title: "Simple Oracle Streams Replication Configuration", anchor: "STREP056", file: "config_simple.htm" },
  { topic: "chapter", section: "3", title: "Flexible Oracle Streams Replication Configuration", anchor: "STREP007", file: "config_flex.htm" },
  { topic: "chapter", section: "4", title: "Adding to an Oracle Streams Replication Environment", anchor: "STREP058", file: "config_add.htm" },
  { topic: "chapter", section: "5", title: "Configuring Implicit Capture", anchor: "STREP204", file: "ccap.htm" },
  { topic: "chapter", section: "6", title: "Configuring Queues and Propagations", anchor: "STREP205", file: "cprop.htm" },
  { topic: "chapter", section: "7", title: "Configuring Implicit Apply", anchor: "STREP206", file: "capply.htm" },
  { topic: "chapter", section: "8", title: "Instantiation and Oracle Streams Replication", anchor: "STREP012", file: "instant.htm" },
  { topic: "chapter", section: "9", title: "Oracle Streams Conflict Resolution", anchor: "STREP001", file: "conflict.htm" },
  { topic: "chapter", section: "10", title: "Oracle Streams Tags", anchor: "STREP008", file: "rep_tags.htm" },
  { topic: "chapter", section: "11", title: "Oracle Streams Heterogeneous Information\u00A0Sharing", anchor: "STREP006", file: "hetero.htm" },
  { topic: "chapter", section: "12", title: "Managing Oracle Streams Replication", anchor: "STREP013", file: "man_gen_rep.htm" },
  { topic: "chapter", section: "13", title: "Comparing and Converging Data", anchor: "STREP146", file: "man_comp.htm" },
  { topic: "chapter", section: "14", title: "Managing Logical Change Records (LCRs)", anchor: "STREP009", file: "man_lcrs.htm" },
  { topic: "chapter", section: "15", title: "Best Practices for Oracle Streams Replication Databases", anchor: "STREP501", file: "best_gen.htm" },
  { topic: "chapter", section: "16", title: "Best Practices for Capture", anchor: "STREP519", file: "best_capture.htm" },
  { topic: "chapter", section: "17", title: "Best Practices for Propagation", anchor: "STREP152", file: "best_prop.htm" },
  { topic: "chapter", section: "18", title: "Best Practices for Apply", anchor: "STREP534", file: "best_apply.htm" },
  { topic: "appendix", section: "A", title: "Migrating Advanced Replication to Oracle Streams", anchor: "STREP125", file: "rep2strm.htm" },
  { } ];
