var chapters = [
  { topic: "chapter", section: "", title: "   Introduction to Large Objects and SecureFiles", anchor: "ADLOB001", file: "adlob_intro.htm" },
  { topic: "chapter", section: "", title: " Working with LOBs", anchor: "ADLOB002", file: "adlob_working.htm" },
  { topic: "chapter", section: "", title: " Managing LOBs: Database Administration", anchor: "ADLOB45150", file: "adlob_managing.htm" },
  { topic: "chapter", section: "", title: " Using Oracle LOB Storage", anchor: "ADLOB4444", file: "adlob_smart.htm" },
  { topic: "chapter", section: "", title: " Introducing the Database File System ", anchor: "ADLOB45943", file: "adlob_fs.htm" },
  { topic: "chapter", section: "", title: " DBFS SecureFiles Store ", anchor: "ADLOB4594", file: "adlob_sfstore.htm" },
  { topic: "chapter", section: "", title: "   DBFS Hierarchical Store", anchor: "ADLOB006", file: "adlob_hierarch.htm" },
  { topic: "chapter", section: "", title: "   DBFS Content API", anchor: "ADLOB007", file: "adlob_cont.htm" },
  { topic: "chapter", section: "", title: "   Creating Your Own DBFS Store", anchor: "ADLOB0079", file: "adlob_dbstore.htm" },
  { topic: "chapter", section: "", title: "   Using DBFS", anchor: "ADLOB0006", file: "adlob_client.htm" },
  { topic: "chapter", section: "", title: " LOB Storage with Applications", anchor: "ADLOB45259", file: "adlob_tables.htm" },
  { topic: "chapter", section: "", title: " Advanced Design Considerations", anchor: "ADLOB45318", file: "adlob_design.htm" },
  { topic: "chapter", section: "", title: " Overview of Supplied LOB APIs", anchor: "ADLOB45356", file: "adlob_api_overview.htm" },
  { topic: "chapter", section: "", title: " Performance Guidelines", anchor: "ADLOB45549", file: "adlob_performance.htm" },
  { topic: "chapter", section: "", title: " DDL and DML Statements with LOBs", anchor: "ADLOB45560", file: "adlob_ddl.htm" },
  { topic: "chapter", section: "", title: " SQL Semantics and LOBs", anchor: "ADLOB010", file: "adlob_sql_semantics.htm" },
  { topic: "chapter", section: "", title: " PL/SQL Semantics for LOBs", anchor: "ADLOB45599", file: "adlob_plsql_semantics.htm" },
  { topic: "chapter", section: "", title: " Migrating Columns from LONGs to LOBs", anchor: "ADLOB008", file: "adlob_long_lob.htm" },
  { topic: "chapter", section: "", title: " Operations Specific to Persistent and Temporary LOBs", anchor: "ADLOB45635", file: "adlob_creating.htm" },
  { topic: "chapter", section: "", title: " Data Interface for Persistent LOBs", anchor: "ADLOB1300", file: "adlob_data_interface.htm" },
  { topic: "chapter", section: "", title: " LOB APIs for BFILE Operations", anchor: "ADLOB012", file: "adlob_bfile_ops.htm" },
  { topic: "chapter", section: "", title: " Using LOB APIs ", anchor: "ADLOB1400", file: "adlob_lob_ops.htm" },
  { topic: "appendix", section: "", title: " LOB Demonstration Files", anchor: "ADLOB45913", file: "adlob_demo.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "ADLOB45922", file: "glossary.htm" },
  { } ];
