var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Database Gateway for APPC", anchor: "APPCI101", file: "ch1.htm" },
  { topic: "chapter", section: "2", title: "Release Information", anchor: "APPCI115", file: "ch2.htm" },
  { topic: "chapter", section: "3", title: "System Requirements", anchor: "APPCI119", file: "ch3.htm" },
  { topic: "chapter", section: "4", title: "Installing the Gateway", anchor: "APPCI134", file: "ch4.htm" },
  { topic: "chapter", section: "5", title: "Configuring Your Oracle Network", anchor: "APPCI160", file: "ch5.htm" },
  { topic: "chapter", section: "6", title: "Configuring the SNA Communication Package on Linux", anchor: "APPCI299", file: "ch6.htm" },
  { topic: "chapter", section: "7", title: "	Configuring the SNA Communication Package on AIX-Based Systems", anchor: "APPCI162", file: "ch7.htm" },
  { topic: "chapter", section: "8", title: "Configuring the SNA Communication Package on Solaris", anchor: "APPCI189", file: "ch9.htm" },
  { topic: "chapter", section: "9", title: "Gateway Configuration Using SNA Communication Protocol", anchor: "APPCI216", file: "ch12.htm" },
  { topic: "chapter", section: "10", title: "Configuring the OLTP", anchor: "APPCI210", file: "ch11.htm" },
  { topic: "chapter", section: "11", title: "Gateway Configuration Using TCP/IP Communication Protocol", anchor: "APPCI239", file: "ch13.htm" },
  { topic: "chapter", section: "12", title: "Security Requirements", anchor: "APPCI256", file: "ch14.htm" },
  { topic: "chapter", section: "13", title: "Migration From Existing Gateways", anchor: "APPCI272", file: "ch15.htm" },
  { topic: "appendix", section: "A", title: "Gateway Initialization Parameters for SNA Protocol", anchor: "APPCI283", file: "apa.htm" },
  { topic: "appendix", section: "B", title: "Gateway Initialization Parameters for TCP/IP Communication Protocol", anchor: "APPCI290", file: "apb.htm" },
  { topic: "appendix", section: "C", title: "Gateway Terminology", anchor: "APPCI296", file: "apc.htm" },
  { topic: "appendix", section: "D", title: "Configuration Worksheet", anchor: "APPCI298", file: "ape.htm" },
  { } ];
