var chapters = [
  { topic: "chapter", section: "1", title: " RDF Semantic Graph Overview", anchor: "RDFRM100", file: "rdf-overview.htm" },
  { topic: "chapter", section: "2", title: " OWL Concepts ", anchor: "RDFRM200", file: "owl-concepts.htm" },
  { topic: "chapter", section: "3", title: "Simple Knowledge Organization System (SKOS) Support ", anchor: "RDFRM99911", file: "skos.htm" },
  { topic: "chapter", section: "4", title: "Semantic Indexing for Documents ", anchor: "RDFRM99921", file: "semantic-indexing-docs.htm" },
  { topic: "chapter", section: "5", title: "Fine-Grained Access Control for RDF Data ", anchor: "RDFRM99941", file: "fine-grained-access.htm" },
  { topic: "chapter", section: "6", title: "Workspace Manager Support for RDF Data ", anchor: "RDFRM99965", file: "wm-rdf.htm" },
  { topic: "chapter", section: "7", title: "RDF Semantic Graph Support for Apache Jena ", anchor: "RDFRM234", file: "rdf-jena.htm" },
  { topic: "chapter", section: "8", title: "RDF Semantic Graph Support for OpenRDF Sesame ", anchor: "RDFRM305", file: "rdf-sesame.htm" },
  { topic: "chapter", section: "9", title: " User-Defined Inferencing and Querying ", anchor: "RDFRM519", file: "user-defined-inf.htm" },
  { topic: "chapter", section: "10", title: " RDF Views: Relational Data as RDF ", anchor: "RDFRM555", file: "rdf-views.htm" },
  { topic: "chapter", section: "11", title: " SEM_APIS Package Subprograms", anchor: "RDFRM500", file: "sem-apis-ref.htm" },
  { topic: "chapter", section: "12", title: " SEM_OLS Package Subprograms", anchor: "RDFRM395", file: "sem-ols-ref.htm" },
  { topic: "chapter", section: "13", title: " SEM_PERF Package Subprograms", anchor: "RDFRM550", file: "sem-perf-ref.htm" },
  { topic: "chapter", section: "14", title: " SEM_RDFCTX Package Subprograms", anchor: "RDFRM800", file: "sem-rdfctx-ref.htm" },
  { topic: "chapter", section: "15", title: " SEM_RDFSA Package Subprograms", anchor: "RDFRM99999", file: "sem-rdfsa-ref.htm" },
  { topic: "appendix", section: "A", title: " Enabling, Downgrading, or Removing RDF Semantic Graph Support", anchor: "RDFRM118", file: "enabling-rdf.htm" },
  { topic: "appendix", section: "B", title: "SEM_MATCH Support for Spatial Queries", anchor: "RDFRM400", file: "sem-match-spatial.htm" },
  { topic: "appendix", section: "C", title: "Virtual Private Database Support in RDF Semantic Graph", anchor: "RDFRM723", file: "rdf-vpd.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "RDFRM415", file: "GUID-E57849D7-DDB7-4219-8687-90D870DD8630.htm" },
  { } ];
