var chapters = [
  { topic: "chapter", section: "1", title: "SQL*Plus User Interface", anchor: "SQPUG008", file: "ch_one.htm" },
  { topic: "chapter", section: "2", title: "Configuring SQL*Plus", anchor: "SQPUG012", file: "ch_two.htm" },
  { topic: "chapter", section: "3", title: "Starting SQL*Plus", anchor: "SQPUG013", file: "ch_three.htm" },
  { topic: "chapter", section: "4", title: "SQL*Plus Basics", anchor: "SQPUG014", file: "ch_four.htm" },
  { topic: "chapter", section: "5", title: "Using Scripts in SQL*Plus", anchor: "SQPUG015", file: "ch_five.htm" },
  { topic: "chapter", section: "6", title: "Formatting SQL*Plus Reports", anchor: "SQPUG016", file: "ch_six.htm" },
  { topic: "chapter", section: "7", title: "Generating HTML Reports from SQL*Plus", anchor: "SQPUG017", file: "ch_seven.htm" },
  { topic: "chapter", section: "8", title: "Tuning SQL*Plus", anchor: "SQPUG018", file: "ch_eight.htm" },
  { topic: "chapter", section: "9", title: "SQL*Plus Security", anchor: "SQPUG019", file: "ch_nine.htm" },
  { topic: "chapter", section: "10", title: "Database Administration with SQL*Plus", anchor: "SQPUG020", file: "ch_ten.htm" },
  { topic: "chapter", section: "11", title: "SQL*Plus Globalization Support", anchor: "SQPUG021", file: "ch_eleven.htm" },
  { topic: "chapter", section: "12", title: "SQL*Plus Command Reference", anchor: "SQPUG022", file: "ch_twelve.htm" },
  { topic: "chapter", section: "13", title: "SQL*Plus Error Messages", anchor: "SQPUG138", file: "ch_thirteen.htm" },
  { topic: "appendix", section: "A", title: "SQL*Plus Limits", anchor: "SQPUG141", file: "apa.htm" },
  { topic: "appendix", section: "B", title: "SQL*Plus COPY Command", anchor: "SQPUG140", file: "apb.htm" },
  { topic: "appendix", section: "C", title: "Obsolete SQL*Plus Commands", anchor: "SQPUG142", file: "apc.htm" },
  { topic: "appendix", section: "D", title: "SQL*Plus Instant Client", anchor: "SQPUG157", file: "apd.htm" },
  { } ];
