var chapters = [
  { topic: "chapter", section: "1", title: "Oracle Database Installation Checklist", anchor: "AXDBI8045", file: "chklist.htm" },
  { topic: "chapter", section: "2", title: "Overview of Oracle Database Installation", anchor: "AXDBI7430", file: "install_overview.htm" },
  { topic: "chapter", section: "3", title: "	Oracle Database Preinstallation Tasks", anchor: "AXDBI222", file: "pre_install.htm" },
  { topic: "chapter", section: "4", title: "Configuring Users, Groups and Environments for Oracle Database", anchor: "AXDBI7652", file: "usr_grps.htm" },
  { topic: "chapter", section: "5", title: "Oracle Grid Infrastructure for a Standalone Server", anchor: "AXDBI999", file: "oraclerestart.htm" },
  { topic: "chapter", section: "6", title: "Installing Oracle Database", anchor: "AXDBI7726", file: "inst_task.htm" },
  { topic: "chapter", section: "7", title: "Oracle Database Postinstallation Tasks", anchor: "AXDBI7744", file: "post_inst_task.htm" },
  { topic: "chapter", section: "8", title: "Getting Started with Oracle Database", anchor: "AXDBI006", file: "rev_precon_db.htm" },
  { topic: "chapter", section: "9", title: "Removing Oracle Database Software", anchor: "AXDBI7824", file: "remove_oracle_sw.htm" },
  { topic: "appendix", section: "A", title: "Installing and Configuring Oracle Database Using Response Files", anchor: "AXDBI7831", file: "app_nonint.htm" },
  { topic: "appendix", section: "B", title: "Cloning an Oracle Home", anchor: "AXDBI7852", file: "app_cloning.htm" },
  { topic: "appendix", section: "C", title: "Using NAS Devices", anchor: "AXDBI7855", file: "app_nas.htm" },
  { topic: "appendix", section: "D", title: "How to Complete Preinstallation Tasks Manually", anchor: "AXDBI7864", file: "app_manual.htm" },
  { topic: "appendix", section: "E", title: "Configuring Networks for Oracle Database", anchor: "AXDBI7891", file: "app_network.htm" },
  { topic: "appendix", section: "F", title: "Optimal Flexible Architecture", anchor: "AXDBI0015", file: "appendix_ofa.htm" },
  { topic: "appendix", section: "G", title: "Managing Oracle Database Port Numbers", anchor: "AXDBI7924", file: "app_port.htm" },
  { topic: "appendix", section: "H", title: "Configuring Oracle Database Globalization Support", anchor: "AXDBI7932", file: "app_glblsupp.htm" },
  { topic: "appendix", section: "I", title: "Troubleshooting", anchor: "AXDBI7939", file: "app_ts.htm" },
  { topic: "appendix", section: "J", title: "Frequently Asked Questions About Installation", anchor: "AXDBI7957", file: "app_faq.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "AXDBI7986", file: "glossary.htm" },
  { } ];
