var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Multimedia DICOM", anchor: "IMDCM1000", file: "ch_intro.htm" },
  { topic: "chapter", section: "2", title: "Oracle Multimedia DICOM Concepts", anchor: "IMDCM1500", file: "ch_cncpt.htm" },
  { topic: "chapter", section: "3", title: "Overview of DICOM Development", anchor: "IMDCM2000", file: "ch_gen_over.htm" },
  { topic: "chapter", section: "4", title: "DICOM Protocol Support", anchor: "IMDCM13885", file: "ch_gen_prtcl.htm" },
  { topic: "chapter", section: "5", title: "DICOM Data Model Utility Reference", anchor: "IMDCM3000", file: "ch_dtmod_ref.htm" },
  { topic: "chapter", section: "6", title: "DICOM Application Development", anchor: "IMDCM5000", file: "ch_dev_apps.htm" },
  { topic: "chapter", section: "7", title: "DICOM Sample Application", anchor: "IMDCM13429", file: "ch_dev_dcmdemo.htm" },
  { topic: "chapter", section: "8", title: "ORDDicom Object Type Reference", anchor: "IMDCM4000", file: "ch_dev_ref.htm" },
  { topic: "chapter", section: "9", title: "DICOM Relational Interface Reference", anchor: "IMDCM6000", file: "ch_rel_ref.htm" },
  { topic: "chapter", section: "10", title: "Overview of DICOM Administration", anchor: "IMDCM7000", file: "ch_adm_over.htm" },
  { topic: "chapter", section: "11", title: "Creating DICOM Configuration Documents", anchor: "IMDCM9500", file: "ch_dtmod_docs.htm" },
  { topic: "chapter", section: "12", title: "Administering the DICOM Repository", anchor: "IMDCM9000", file: "ch_adm_repos.htm" },
  { topic: "chapter", section: "13", title: "ORD_DICOM_ADMIN Package Reference", anchor: "IMDCM8000", file: "ch_adm_ref.htm" },
  { topic: "appendix", section: "A", title: "DICOM Configuration Documents", anchor: "IMDCM10000", file: "ap_confg_docs.htm" },
  { topic: "appendix", section: "B", title: "DICOM XML Schemas", anchor: "IMDCM11000", file: "ap_schemas.htm" },
  { topic: "appendix", section: "C", title: "DICOM Encoding Rules", anchor: "IMDCM12000", file: "ap_encdg_rls.htm" },
  { topic: "appendix", section: "D", title: "DICOM Processing and Supported Formats", anchor: "IMDCM12500", file: "ap_img_proc.htm" },
  { topic: "appendix", section: "E", title: "DICOM Sample Applications", anchor: "IMDCM13520", file: "ap_dcm_demos.htm" },
  { topic: "appendix", section: "F", title: "Migrating from Oracle Database 10g Release 2 (10.2) DICOM Support", anchor: "IMDCM13000", file: "ap_migrate.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "IMDCM13521", file: "dm_glossary.htm" },
  { } ];
