var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle SQL", anchor: "SQLRF001", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Basic Elements of Oracle SQL", anchor: "SQLRF002", file: "sql_elements.htm" },
  { topic: "chapter", section: "3", title: "Pseudocolumns", anchor: "SQLRF0025", file: "pseudocolumns.htm" },
  { topic: "chapter", section: "4", title: "Operators", anchor: "SQLRF003", file: "operators.htm" },
  { topic: "chapter", section: "5", title: "Expressions", anchor: "SQLRF004", file: "expressions.htm" },
  { topic: "chapter", section: "6", title: "Conditions", anchor: "SQLRF005", file: "conditions.htm" },
  { topic: "chapter", section: "7", title: "Functions", anchor: "SQLRF006", file: "functions.htm" },
  { topic: "chapter", section: "8", title: "Common SQL DDL Clauses", anchor: "SQLRF021", file: "clauses.htm" },
  { topic: "chapter", section: "9", title: "SQL Queries and Subqueries", anchor: "SQLRF007", file: "queries.htm" },
  { topic: "chapter", section: "10", title: "SQL Statements: ADMINISTER KEY MANAGEMENT to ALTER JAVA", anchor: "SQLRF008", file: "statements_1.htm" },
  { topic: "chapter", section: "11", title: "SQL Statements: ALTER LIBRARY to ALTER SYSTEM", anchor: "SQLRF009", file: "statements_2.htm" },
  { topic: "chapter", section: "12", title: "SQL Statements: ALTER TABLE to ALTER\u00A0TABLESPACE", anchor: "SQLRF010", file: "statements_3.htm" },
  { topic: "chapter", section: "13", title: "SQL Statements: ALTER TRIGGER to COMMIT", anchor: "SQLRF011", file: "statements_4.htm" },
  { topic: "chapter", section: "14", title: "SQL Statements: CREATE AUDIT POLICY to CREATE JAVA", anchor: "SQLRF012", file: "statements_5.htm" },
  { topic: "chapter", section: "15", title: "SQL Statements: CREATE LIBRARY to CREATE SPFILE", anchor: "SQLRF013", file: "statements_6.htm" },
  { topic: "chapter", section: "16", title: "SQL Statements: CREATE SYNONYM to CREATE TRIGGER", anchor: "SQLRF014", file: "statements_7.htm" },
  { topic: "chapter", section: "17", title: "SQL Statements: CREATE TYPE to DROP\u00A0ROLLBACK SEGMENT", anchor: "SQLRF54727", file: "statements_8.htm" },
  { topic: "chapter", section: "18", title: "SQL Statements: DROP SEQUENCE to ROLLBACK", anchor: "SQLRF016", file: "statements_9.htm" },
  { topic: "chapter", section: "19", title: "SQL Statements: SAVEPOINT to UPDATE", anchor: "SQLRF017", file: "statements_10.htm" },
  { topic: "appendix", section: "A", title: "How to Read Syntax Diagrams", anchor: "SQLRF018", file: "ap_syntx.htm" },
  { topic: "appendix", section: "B", title: "Automatic and Manual Locking Mechanisms During SQL Operations", anchor: "SQLRF55501", file: "ap_locks.htm" },
  { topic: "appendix", section: "C", title: "Oracle and Standard SQL", anchor: "SQLRF019", file: "ap_standard_sql.htm" },
  { topic: "appendix", section: "D", title: "Oracle Regular Expression Support", anchor: "SQLRF020", file: "ap_posix.htm" },
  { topic: "appendix", section: "E", title: "Oracle SQL Reserved Words and Keywords", anchor: "SQLRF022", file: "ap_keywd.htm" },
  { topic: "appendix", section: "F", title: "Extended Examples", anchor: "SQLRF55546", file: "ap_examples.htm" },
  { } ];
