var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Database Provider for DRDA", anchor: "DRDAS109", file: "introduction.htm" },
  { topic: "chapter", section: "2", title: "Architecture of Oracle Database Provider for DRDA", anchor: "DRDAS120", file: "architecture.htm" },
  { topic: "chapter", section: "3", title: "Installation and Configuration of Oracle Database Provider for DRDA", anchor: "DRDAS137", file: "install_config.htm" },
  { topic: "chapter", section: "4", title: "SQL Translation and Examples for Oracle Database Provider for DRDA", anchor: "DRDAS196", file: "translation_examples.htm" },
  { topic: "chapter", section: "5", title: "Administration and Customization of Oracle Database Provider for DRDA", anchor: "DRDAS219", file: "customization.htm" },
  { topic: "chapter", section: "6", title: "Diagnostics and Maintenance of Oracle Database Provider for DRDA", anchor: "DRDAS233", file: "diagnostics.htm" },
  { topic: "chapter", section: "7", title: "Data Type Support and Conversion in Oracle Database Provider for DRDA", anchor: "DRDAS241", file: "data_type.htm" },
  { topic: "chapter", section: "8", title: "Data Dictionary for Oracle Database Provider for DRDA", anchor: "DRDAS488", file: "data_dictionary.htm" },
  { topic: "chapter", section: "9", title: "Error Codes Support in Oracle Database Provider for DRDA", anchor: "DRDAS513", file: "error_code.htm" },
  { topic: "chapter", section: "10", title: "Command-line Utility for Oracle Database Provider for DRDA", anchor: "DRDAS516", file: "command_line_util.htm" },
  { topic: "chapter", section: "11", title: "Security and Storage Considerations for Oracle Database Provider for DRDA", anchor: "DRDAS538", file: "security.htm" },
  { topic: "chapter", section: "12", title: "Restrictions on Using Oracle Database Provider for DRDA", anchor: "DRDAS642", file: "restrictions.htm" },
  { topic: "chapter", section: "13", title: "PL/SQL Packages Used by Oracle Database Provider for DRDA", anchor: "DRDAS547", file: "pl_sql.htm" },
  { topic: "chapter", section: "14", title: "SQL Statements Supported by Oracle Database Provider for DRDA", anchor: "CJACCFHC", file: "sql_clauses.htm" },
  { topic: "appendix", section: "A", title: "Scripts for Creating and Maintaining Oracle Database Provider for DRDA", anchor: "DRDAS601", file: "scripts_appendix.htm" },
  { topic: "appendix", section: "B", title: "Package Binding Options in Oracle Database Provider for DRDA", anchor: "DRDAS679", file: "bind_appendix.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "DRDAS604", file: "glossary.htm" },
  { } ];
