var chapters = [
  { topic: "chapter", section: "", title: " Introduction to Oracle Database Security", anchor: "DBSEG001", file: "intro.htm" },
  { topic: "chapter", section: "", title: "Managing Security for Oracle Database Users", anchor: "DBSEG002", file: "users.htm" },
  { topic: "chapter", section: "", title: " Configuring Authentication", anchor: "DBSEG003", file: "authentication.htm" },
  { topic: "chapter", section: "", title: "Configuring Privilege and Role Authorization", anchor: "DBSEG004", file: "authorization.htm" },
  { topic: "chapter", section: "", title: "Managing Security for Definer's Rights and\u00A0Invoker's Rights ", anchor: "DBSEG658", file: "dr_ir.htm" },
  { topic: "chapter", section: "", title: "Managing Fine-Grained Access in\u00A0PL/SQL\u00A0Packages and Types", anchor: "DBSEG40012", file: "fine_grained_access.htm" },
  { topic: "chapter", section: "", title: "Managing Security for a Multitenant Environment in\u00A0Enterprise Manager", anchor: "DBSEG906", file: "cdb_security.htm" },
  { topic: "chapter", section: "", title: " Managing Security for Application\u00A0Developers", anchor: "DBSEG005", file: "app_devs.htm" },
  { topic: "chapter", section: "", title: "Using Application Contexts to\u00A0Retrieve\u00A0User\u00A0Information", anchor: "DBSEG011", file: "app_context.htm" },
  { topic: "chapter", section: "", title: "Using Oracle Virtual Private Database to\u00A0Control\u00A0Data Access", anchor: "DBSEG007", file: "vpd.htm" },
  { topic: "chapter", section: "", title: "Using Transparent Sensitive Data Protection ", anchor: "DBSEG855", file: "tsdp.htm" },
  { topic: "chapter", section: "", title: " Manually Encrypting Data", anchor: "DBSEG008", file: "data_encryption.htm" },
  { topic: "chapter", section: "", title: "Configuring Oracle Database Network Encryption and\u00A0Data Integrity", anchor: "DBSEG020", file: "asoconfg.htm" },
  { topic: "chapter", section: "", title: " Configuring the Thin JDBC Client Network", anchor: "DBSEG030", file: "asojbdc.htm" },
  { topic: "chapter", section: "", title: "Introduction to Strong Authentication", anchor: "DBSEG491", file: "strong_auth.htm" },
  { topic: "chapter", section: "", title: " Strong Authentication Administration Tools", anchor: "DBSEG451", file: "asotools.htm" },
  { topic: "chapter", section: "", title: " Configuring Kerberos Authentication ", anchor: "DBSEG060", file: "asokerb.htm" },
  { topic: "chapter", section: "", title: " Configuring Secure Sockets Layer Authentication", anchor: "DBSEG070", file: "asossl.htm" },
  { topic: "chapter", section: "", title: " Configuring RADIUS Authentication", anchor: "DBSEG040", file: "asoradus.htm" },
  { topic: "chapter", section: "", title: " Customizing the Use of Strong Authentication", anchor: "DBSEG090", file: "asoauth.htm" },
  { topic: "chapter", section: "", title: "Introduction to Auditing", anchor: "DBSEG1023", file: "auditing.htm" },
  { topic: "chapter", section: "", title: "Configuring Audit Policies", anchor: "DBSEG1025", file: "audit_config.htm" },
  { topic: "chapter", section: "", title: "Administering the Audit Trail", anchor: "DBSEG1026", file: "audit_admin.htm" },
  { topic: "appendix", section: "", title: "Keeping Your Oracle Database Secure", anchor: "DBSEG009", file: "guidelines.htm" },
  { topic: "appendix", section: "", title: " Data Encryption and Integrity Parameters", anchor: "DBSEG544", file: "asoappa.htm" },
  { topic: "appendix", section: "", title: " Kerberos, SSL, and RADIUS Authentication\u00A0Parameters", anchor: "DBSEG596", file: "asoappb.htm" },
  { topic: "appendix", section: "", title: " Integrating Authentication Devices Using\u00A0RADIUS", anchor: "DBSEG604", file: "asoappc.htm" },
  { topic: "appendix", section: "", title: " Oracle Database FIPS 140-2 Settings", anchor: "DBSEG1041", file: "asoappe.htm" },
  { topic: "appendix", section: "", title: " Using the orapki Utility to\u00A0Manage\u00A0PKI\u00A0Elements", anchor: "DBSEG610", file: "asoappf.htm" },
  { topic: "appendix", section: "", title: "How the Unified Auditing Migration Affects Individual Audit Features", anchor: "DBSEG341", file: "audit_changes.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "DBSEG010", file: "glossary.htm" },
  { } ];
