var chapters = [
  { topic: "chapter", section: "1", title: "Introduction", anchor: "LNPCC3028", file: "pc_01int.htm" },
  { topic: "chapter", section: "2", title: "Precompiler Concepts", anchor: "LNPCC3059", file: "pc_02prc.htm" },
  { topic: "chapter", section: "3", title: "Database Concepts", anchor: "LNPCC3108", file: "pc_03dbc.htm" },
  { topic: "chapter", section: "4", title: "Datatypes and Host Variables", anchor: "LNPCC3154", file: "pc_04dat.htm" },
  { topic: "chapter", section: "5", title: "Advanced Topics", anchor: "LNPCC3253", file: "pc_05adv.htm" },
  { topic: "chapter", section: "6", title: "Embedded SQL", anchor: "LNPCC3339", file: "pc_06sql.htm" },
  { topic: "chapter", section: "7", title: "		Embedded PL/SQL", anchor: "LNPCC3397", file: "pc_07pls.htm" },
  { topic: "chapter", section: "8", title: "Host Arrays", anchor: "LNPCC3433", file: "pc_08arr.htm" },
  { topic: "chapter", section: "9", title: "Handling Runtime Errors", anchor: "LNPCC3490", file: "pc_09err.htm" },
  { topic: "chapter", section: "10", title: "	Precompiler Options", anchor: "LNPCC3574", file: "pc_10opt.htm" },
  { topic: "chapter", section: "11", title: "Multithreaded Applications", anchor: "LNPCC3942", file: "pc_11thr.htm" },
  { topic: "chapter", section: "12", title: "C++ Applications", anchor: "LNPCC012", file: "pc_12cpl.htm" },
  { topic: "chapter", section: "13", title: "Oracle Dynamic SQL", anchor: "LNPCC3991", file: "pc_13dyn.htm" },
  { topic: "chapter", section: "14", title: "	ANSI Dynamic SQL", anchor: "LNPCC014", file: "pc_14ady.htm" },
  { topic: "chapter", section: "15", title: "Oracle Dynamic SQL: Method 4", anchor: "LNPCC015", file: "pc_15ody.htm" },
  { topic: "chapter", section: "16", title: "LOBs", anchor: "LNPCC016", file: "pc_16lob.htm" },
  { topic: "chapter", section: "17", title: "Objects", anchor: "LNPCC017", file: "pc_17obj.htm" },
  { topic: "chapter", section: "18", title: "Collections", anchor: "LNPCC4375", file: "pc_18col.htm" },
  { topic: "chapter", section: "19", title: "The Object Type Translator", anchor: "LNPCC019", file: "pc_19ott.htm" },
  { topic: "chapter", section: "20", title: "User Exits", anchor: "LNPCC4492", file: "pc_20exi.htm" },
  { topic: "appendix", section: "A", title: "	Reserved Words, Keywords, and Namespaces", anchor: "LNPCC022", file: "pc_abres.htm" },
  { topic: "appendix", section: "B", title: "	Performance Tuning", anchor: "LNPCC023", file: "pc_actun.htm" },
  { topic: "appendix", section: "C", title: "Syntactic and Semantic Checking", anchor: "LNPCC024", file: "pc_adchk.htm" },
  { topic: "appendix", section: "D", title: "	System-Specific References", anchor: "LNPCC025", file: "pc_aeops.htm" },
  { topic: "appendix", section: "E", title: "	Embedded SQL Statements and Directives", anchor: "LNPCC020", file: "pc_afemb.htm" },
  { topic: "appendix", section: "F", title: "Sample Programs", anchor: "LNPCC5122", file: "pc_agsmp.htm" },
  { topic: "appendix", section: "G", title: "Integrating Pro*C/C++ into Microsoft Visual Studio .NET", anchor: "LNPCC5130", file: "pc_ahintegrat.htm" },
  { } ];
