var chapters = [
  { topic: "chapter", section: "1", title: "APEX_APPLICATION", anchor: "AEAPI214", file: "apex_app.htm" },
  { topic: "chapter", section: "2", title: "APEX_APPLICATION_INSTALL", anchor: "AEAPI530", file: "apex_app_inst.htm" },
  { topic: "chapter", section: "3", title: "APEX_AUTHENTICATION", anchor: "AEAPI29130", file: "apex_authentication.htm" },
  { topic: "chapter", section: "4", title: "APEX_COLLECTION", anchor: "AEAPI531", file: "apex_collection.htm" },
  { topic: "chapter", section: "5", title: "APEX_CSS", anchor: "AEAPI532", file: "apex_css.htm" },
  { topic: "chapter", section: "6", title: "APEX_CUSTOM_AUTH", anchor: "AEAPI218", file: "apex_auth.htm" },
  { topic: "chapter", section: "7", title: "APEX_DEBUG", anchor: "AEAPI29182", file: "apex_debug.htm" },
  { topic: "chapter", section: "8", title: "APEX_ERROR", anchor: "AEAPI2209", file: "apex_error.htm" },
  { topic: "chapter", section: "9", title: "APEX_ESCAPE", anchor: "AEAPI29268", file: "apex_escape.htm" },
  { topic: "chapter", section: "10", title: "APEX_INSTANCE_ADMIN", anchor: "AEAPI245", file: "apex_instance.htm" },
  { topic: "chapter", section: "11", title: "APEX_IR", anchor: "AEAPI29337", file: "apex_ir.htm" },
  { topic: "chapter", section: "12", title: "APEX_ITEM", anchor: "AEAPI192", file: "apex_item.htm" },
  { topic: "chapter", section: "13", title: "APEX_JAVASCRIPT", anchor: "AEAPI534", file: "apex_javascript.htm" },
  { topic: "chapter", section: "14", title: "APEX_LANG", anchor: "AEAPI354", file: "apex_lang.htm" },
  { topic: "chapter", section: "15", title: "APEX_LDAP", anchor: "AEAPI238", file: "apex_ldap.htm" },
  { topic: "chapter", section: "16", title: "APEX_MAIL", anchor: "AEAPI341", file: "apex_mail.htm" },
  { topic: "chapter", section: "17", title: "APEX_PLSQL_JOB", anchor: "AEAPI353", file: "apex_plsql_job.htm" },
  { topic: "chapter", section: "18", title: "APEX_PLUGIN", anchor: "AEAPI535", file: "apex_plugin.htm" },
  { topic: "chapter", section: "19", title: "APEX_PLUGIN_UTIL", anchor: "AEAPI536", file: "apex_plugin_util.htm" },
  { topic: "chapter", section: "20", title: "APEX_UI_DEFAULT_UPDATE", anchor: "AEAPI254", file: "apex_ui_default.htm" },
  { topic: "chapter", section: "21", title: "APEX_UTIL", anchor: "AEAPI101", file: "apex_util.htm" },
  { topic: "chapter", section: "22", title: "APEX_WEB_SERVICE", anchor: "AEAPI537", file: "apex_web_service.htm" },
  { topic: "chapter", section: "23", title: "JavaScript APIs", anchor: "AEAPI266", file: "javascript_api.htm" },
  { } ];
