var chapters = [
  { topic: "chapter", section: "", title: " Performance Tuning Overview", anchor: "TGDBA025", file: "pfgrf_perf_overview.htm" },
  { topic: "chapter", section: "", title: " Designing and Developing for Performance", anchor: "TGDBA030", file: "pfgrf_design.htm" },
  { topic: "chapter", section: "", title: " Performance Improvement Methods", anchor: "TGDBA032", file: "pfgrf_technique.htm" },
  { topic: "chapter", section: "", title: "Configuring a Database for Performance", anchor: "TGDBA013", file: "pfgrf_build_db.htm" },
  { topic: "chapter", section: "", title: "Measuring Database Performance ", anchor: "TGDBA145", file: "measure_db.htm" },
  { topic: "chapter", section: "", title: "Gathering Database Statistics ", anchor: "TGDBA167", file: "gather_stats.htm" },
  { topic: "chapter", section: "", title: "Automatic Performance Diagnostics ", anchor: "TGDBA026", file: "pfgrf_diag.htm" },
  { topic: "chapter", section: "", title: "Comparing Database Performance Over Time ", anchor: "TGDBA272", file: "compare_stats.htm" },
  { topic: "chapter", section: "", title: "Analyzing Sampled Data ", anchor: "TGDBA276", file: "sampling.htm" },
  { topic: "chapter", section: "", title: " Instance Tuning Using Performance Views", anchor: "TGDBA024", file: "pfgrf_instance_tune.htm" },
  { topic: "chapter", section: "", title: "Database Memory Allocation ", anchor: "TGDBA291", file: "memory.htm" },
  { topic: "chapter", section: "", title: "Tuning the System Global Area ", anchor: "TGDBA320", file: "tune_sga.htm" },
  { topic: "chapter", section: "", title: "Tuning the Database Buffer Cache ", anchor: "TGDBA294", file: "tune_buffer_cache.htm" },
  { topic: "chapter", section: "", title: "Tuning the Shared Pool and the Large Pool ", anchor: "TGDBA558", file: "tune_shared_pool.htm" },
  { topic: "chapter", section: "", title: "Tuning the Result Cache ", anchor: "TGDBA616", file: "tune_result_cache.htm" },
  { topic: "chapter", section: "", title: "Tuning the Program Global Area ", anchor: "TGDBA346", file: "tune_pga.htm" },
  { topic: "chapter", section: "", title: " I/O Configuration and Design", anchor: "TGDBA015", file: "pfgrf_iodesign.htm" },
  { topic: "chapter", section: "", title: " Managing Operating System Resources", anchor: "TGDBA016", file: "pfgrf_os.htm" },
  { } ];
