var chapters = [
  { topic: "chapter", section: "", title: "Introduction to Oracle Database Vault", anchor: "DVADM001", file: "dvintro.htm" },
  { topic: "chapter", section: "", title: "What to Expect After You Enable Oracle\u00A0Database Vault", anchor: "DVADM018", file: "dv_impact.htm" },
  { topic: "chapter", section: "", title: "Getting Started with Oracle Database Vault", anchor: "DVADM002", file: "getting_started.htm" },
  { topic: "chapter", section: "", title: "Performing Privilege Analysis to\u00A0Find\u00A0Privilege\u00A0Use", anchor: "DVADM591", file: "priv_analysis.htm" },
  { topic: "chapter", section: "", title: "Configuring Realms", anchor: "DVADM003", file: "cfrealms.htm" },
  { topic: "chapter", section: "", title: "Configuring Rule Sets ", anchor: "DVADM006", file: "cfrulset.htm" },
  { topic: "chapter", section: "", title: "Configuring Command Rules ", anchor: "DVADM005", file: "cfcmdaut.htm" },
  { topic: "chapter", section: "", title: "Configuring Factors", anchor: "DVADM004", file: "cfgfact.htm" },
  { topic: "chapter", section: "", title: "Configuring Secure Application Roles for\u00A0Oracle Database Vault", anchor: "DVADM007", file: "cfseappr.htm" },
  { topic: "chapter", section: "", title: "Integrating Oracle Database Vault with Other\u00A0Oracle Products", anchor: "DVADM008", file: "dv_ols.htm" },
  { topic: "chapter", section: "", title: "DBA Operations in an Oracle\u00A0Database\u00A0Vault\u00A0Environment", anchor: "DVADM71122", file: "dba.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Schemas, Roles, and\u00A0Accounts", anchor: "DVADM013", file: "db_objects.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Realm APIs", anchor: "DVADM71188", file: "apis_realms.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Rule Set APIs", anchor: "DVADM71189", file: "apis_rule_sets.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Command Rule APIs", anchor: "DVADM71190", file: "apis_command_rules.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Factor APIs", anchor: "DVADM71191", file: "apis_factors.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Secure\u00A0Application\u00A0Role\u00A0APIs ", anchor: "DVADM71192", file: "apis_roles.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Oracle\u00A0Label\u00A0Security\u00A0APIs", anchor: "DVADM71194", file: "apis_ols.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Utility APIs", anchor: "DVADM020", file: "apis_dbms_macutl.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault General\u00A0Administrative\u00A0APIs", anchor: "DVADM71195", file: "apis_admin.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault API Reference", anchor: "DVADM71196", file: "apis_ref.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Data Dictionary Views", anchor: "DVADM71179", file: "views.htm" },
  { topic: "chapter", section: "", title: "Monitoring Oracle Database Vault", anchor: "DVADM010", file: "monitoring.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Vault Reports", anchor: "DVADM009", file: "reports.htm" },
  { topic: "appendix", section: "", title: "Auditing Oracle Database Vault", anchor: "DVADM011", file: "audplcy.htm" },
  { topic: "appendix", section: "", title: "Disabling and Enabling Oracle\u00A0Database\u00A0Vault", anchor: "DVADM012", file: "dvdisabl.htm" },
  { topic: "appendix", section: "", title: "Postinstallation Oracle\u00A0Database Vault Procedures", anchor: "DVADM022", file: "dvca.htm" },
  { topic: "appendix", section: "", title: "Oracle Database Vault Security Guidelines", anchor: "DVADM019", file: "guidelines.htm" },
  { topic: "appendix", section: "", title: "Troubleshooting Oracle Database Vault", anchor: "DVADM017", file: "troubleshooting.htm" },
  { } ];
