var chapters = [
  { topic: "chapter", section: "1", title: "Quick Start", anchor: "HTMDB01000", file: "start.htm" },
  { topic: "chapter", section: "2", title: "Application Builder Concepts", anchor: "HTMDB03000", file: "concept.htm" },
  { topic: "chapter", section: "3", title: "Utilizing Packaged Applications", anchor: "HTMDB02000", file: "demo.htm" },
  { topic: "chapter", section: "4", title: "Managing the Development Process", anchor: "HTMDB28082", file: "teamdev.htm" },
  { topic: "chapter", section: "5", title: "About Websheet Applications", anchor: "HTMDB28751", file: "bldwebsheet.htm" },
  { topic: "chapter", section: "6", title: "Using Application Builder", anchor: "HTMDB04000", file: "bldr.htm" },
  { topic: "chapter", section: "7", title: "About Database Applications", anchor: "HTMDB05001", file: "bldapp.htm" },
  { topic: "chapter", section: "8", title: "Working with Database Application Pages", anchor: "HTMDB25097", file: "bldr_pgs.htm" },
  { topic: "chapter", section: "9", title: "Creating Reports", anchor: "HTMDB05004", file: "bldapp_rpt.htm" },
  { topic: "chapter", section: "10", title: "Adding Database Application Components and Controls", anchor: "HTMDB25344", file: "app_comp.htm" },
  { topic: "chapter", section: "11", title: "Adding Navigation", anchor: "HTMDB07001", file: "nav.htm" },
  { topic: "chapter", section: "12", title: "Controlling Page Layout", anchor: "HTMDB25564", file: "ui.htm" },
  { topic: "chapter", section: "13", title: "Managing Themes and Templates", anchor: "HTMDB25593", file: "themes.htm" },
  { topic: "chapter", section: "14", title: "Debugging an Application", anchor: "HTMDB10000", file: "debug.htm" },
  { topic: "chapter", section: "15", title: "Managing Application Security", anchor: "HTMDB12000", file: "sec.htm" },
  { topic: "chapter", section: "16", title: "Deploying an Application", anchor: "HTMDB11000", file: "deploy.htm" },
  { topic: "chapter", section: "17", title: "Advanced Programming Techniques", anchor: "HTMDB13000", file: "advnc.htm" },
  { topic: "chapter", section: "18", title: "Managing Application Globalization", anchor: "HTMDB14000", file: "global.htm" },
  { topic: "appendix", section: "A", title: "About Item Types", anchor: "HTMDB28625", file: "item_types.htm" },
  { topic: "appendix", section: "B", title: "Oracle Application Express Limits", anchor: "HTMDB28629", file: "limits.htm" },
  { topic: "appendix", section: "C", title: "Available Conditions", anchor: "HTMDB25942", file: "condition.htm" },
  { topic: "appendix", section: "D", title: "About Granted Privileges", anchor: "HTMDB25944", file: "priv_public.htm" },
  { topic: "appendix", section: "E", title: "Accessibility in Oracle Application Express", anchor: "HTMDB100", file: "accessibility.htm" },
  { } ];
