var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Database Gateway for APPC", anchor: "APPUG100", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Procedural Gateway Administration Utility", anchor: "APPUG200", file: "admin_util.htm" },
  { topic: "chapter", section: "3", title: "Creating a TIP", anchor: "APPUG300", file: "tip.htm" },
  { topic: "chapter", section: "4", title: "Client Application Development (SNA Only)", anchor: "APPUG400", file: "app_sna.htm" },
  { topic: "chapter", section: "5", title: "Implementing Commit-Confirm (SNA Only)", anchor: "APPUG500", file: "com_con.htm" },
  { topic: "chapter", section: "6", title: "PG4TCPMAP Commands (TCP/IP Only)", anchor: "APPUG600", file: "tcpmap.htm" },
  { topic: "chapter", section: "7", title: "Client Application Development (TCP/IP Only)", anchor: "APPUG700", file: "app_tcp.htm" },
  { topic: "chapter", section: "8", title: "Troubleshooting", anchor: "APPUG800", file: "pro_det.htm" },
  { topic: "appendix", section: "A", title: "Database Gateway for APPC Data Dictionary", anchor: "APPUG900", file: "apa.htm" },
  { topic: "appendix", section: "B", title: "Gateway RPC Interface", anchor: "APPUG110", file: "apb.htm" },
  { topic: "appendix", section: "C", title: "The UTL_PG Interface", anchor: "APPUG120", file: "apc.htm" },
  { topic: "appendix", section: "D", title: "Datatype Conversions", anchor: "APPUG1113", file: "apd.htm" },
  { topic: "appendix", section: "E", title: "Tip Internals", anchor: "APPUG130", file: "apf.htm" },
  { topic: "appendix", section: "F", title: "Administration Utility Samples", anchor: "APPUG150", file: "apg.htm" },
  { } ];
