var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Streams", anchor: "STRMS001", file: "strms_over.htm" },
  { topic: "chapter", section: "2", title: "Oracle Streams Information Capture", anchor: "STRMS002", file: "strms_capture.htm" },
  { topic: "chapter", section: "3", title: "Oracle Streams Staging and Propagation", anchor: "STRMS003", file: "strms_prop.htm" },
  { topic: "chapter", section: "4", title: "Oracle Streams Information Consumption", anchor: "STRMS004", file: "strms_apply.htm" },
  { topic: "chapter", section: "5", title: "How Rules Are Used in Oracle Streams", anchor: "STRMS006", file: "strms_rules.htm" },
  { topic: "chapter", section: "6", title: "Rule-Based Transformations", anchor: "STRMS106", file: "strms_transform.htm" },
  { topic: "chapter", section: "7", title: "Advanced Capture Process Concepts", anchor: "STRMS469", file: "strms_adcapture.htm" },
  { topic: "chapter", section: "8", title: "Advanced Queue Concepts", anchor: "STRMS484", file: "strms_adqueue.htm" },
  { topic: "chapter", section: "9", title: "Advanced Propagation Concepts", anchor: "STRMS010", file: "strms_adprop.htm" },
  { topic: "chapter", section: "10", title: "Advanced Apply Process Concepts", anchor: "STRMS497", file: "strms_adapply.htm" },
  { topic: "chapter", section: "11", title: "Advanced Rule Concepts", anchor: "STRMS005", file: "strms_adrules.htm" },
  { topic: "chapter", section: "12", title: "Combined Capture and Apply Optimization", anchor: "STRMS171", file: "strms_adcca.htm" },
  { topic: "chapter", section: "13", title: "Oracle Streams High Availability Environments", anchor: "STRMS007", file: "strms_adha.htm" },
  { topic: "chapter", section: "14", title: "Introduction to Oracle Streams Administration", anchor: "STRMS177", file: "strms_mintro.htm" },
  { topic: "chapter", section: "15", title: "Managing Oracle Streams Implicit Capture", anchor: "STRMS116", file: "strms_mcap.htm" },
  { topic: "chapter", section: "16", title: "Managing Staging and Propagation", anchor: "STRMS011", file: "strms_mprop.htm" },
  { topic: "chapter", section: "17", title: "Managing Oracle Streams Information Consumption", anchor: "STRMS009", file: "strms_mapply.htm" },
  { topic: "chapter", section: "18", title: "Managing Rules", anchor: "STRMS012", file: "strms_mrules.htm" },
  { topic: "chapter", section: "19", title: "Managing Rule-Based Transformations", anchor: "STRMS154", file: "strms_mtransform.htm" },
  { topic: "chapter", section: "20", title: "Using Oracle Streams to Record Table Changes", anchor: "STRMS1519", file: "strms_change_table.htm" },
  { topic: "chapter", section: "21", title: "Other Oracle Streams Management Tasks", anchor: "STRMS013", file: "man_advanced.htm" },
  { topic: "chapter", section: "22", title: "Monitoring an Oracle Streams Environment", anchor: "STRMS118", file: "strms_monitor.htm" },
  { topic: "chapter", section: "23", title: "Monitoring the Oracle Streams Topology and Performance", anchor: "STRMS170", file: "strms_topology.htm" },
  { topic: "chapter", section: "24", title: "Monitoring Oracle Streams Implicit Capture", anchor: "STRMS877", file: "strms_cpmon.htm" },
  { topic: "chapter", section: "25", title: "Monitoring Oracle Streams Queues and Propagations", anchor: "STRMS906", file: "strms_qpmon.htm" },
  { topic: "chapter", section: "26", title: "Monitoring Oracle Streams Apply Processes", anchor: "STRMS940", file: "strms_apmon.htm" },
  { topic: "chapter", section: "27", title: "Monitoring Rules", anchor: "STRMS975", file: "strms_rumon.htm" },
  { topic: "chapter", section: "28", title: "Monitoring Rule-Based Transformations", anchor: "STRMS995", file: "strms_trmon.htm" },
  { topic: "chapter", section: "29", title: "Monitoring Other Oracle Streams Components", anchor: "STRMS1001", file: "strms_otmon.htm" },
  { topic: "chapter", section: "30", title: "Identifying Problems in an Oracle Streams Environment", anchor: "STRMS015", file: "strms_trouble.htm" },
  { topic: "chapter", section: "31", title: "Troubleshooting Implicit Capture", anchor: "STRMS1024", file: "strms_trcapture.htm" },
  { topic: "chapter", section: "32", title: "Troubleshooting Propagation", anchor: "STRMS1040", file: "strms_trprop.htm" },
  { topic: "chapter", section: "33", title: "Troubleshooting Apply", anchor: "STRMS1048", file: "strms_trapply.htm" },
  { topic: "chapter", section: "34", title: "Troubleshooting Rules and Rule-Based Transformations", anchor: "STRMS1075", file: "strms_trrules.htm" },
  { topic: "chapter", section: "35", title: "Information Provisioning Concepts", anchor: "STRMS008", file: "strms_ipro.htm" },
  { topic: "chapter", section: "36", title: "Using Information Provisioning", anchor: "STRMS018", file: "strms_miprov.htm" },
  { topic: "chapter", section: "37", title: "Monitoring File Group and Tablespace Repositories", anchor: "STRMS1140", file: "strms_fgmon.htm" },
  { topic: "appendix", section: "A", title: "How Oracle Streams Works with Other Database Components", anchor: "STRMS1166", file: "ap_other.htm" },
  { topic: "appendix", section: "B", title: "Oracle Streams Restrictions", anchor: "STRMS182", file: "ap_restrictions.htm" },
  { topic: "appendix", section: "C", title: "XML Schema for LCRs", anchor: "STRMS030", file: "ap_xmlschema.htm" },
  { topic: "appendix", section: "D", title: "Online Database Upgrade and Maintenance with Oracle Streams", anchor: "STRMS165", file: "ap_strmnt.htm" },
  { topic: "appendix", section: "E", title: "Online Upgrade of an Earlier Database with Oracle Streams", anchor: "STRMS140", file: "ap_strup.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "STRMS1284", file: "strms_glossary.htm" },
  { } ];
