var chapters = [
  { topic: "chapter", section: "", title: "Introduction to Oracle Database", anchor: "CNCPT001", file: "intro.htm" },
  { topic: "chapter", section: "", title: "Tables and Table Clusters ", anchor: "CNCPT010", file: "tablecls.htm" },
  { topic: "chapter", section: "", title: "Indexes and Index-Organized Tables", anchor: "CNCPT721", file: "indexiot.htm" },
  { topic: "chapter", section: "", title: "Partitions, Views, and Other Schema Objects ", anchor: "CNCPT88858", file: "schemaob.htm" },
  { topic: "chapter", section: "", title: "Data Integrity", anchor: "CNCPT021", file: "datainte.htm" },
  { topic: "chapter", section: "", title: "Data Dictionary and Dynamic Performance Views", anchor: "CNCPT002", file: "datadict.htm" },
  { topic: "chapter", section: "", title: "SQL", anchor: "CNCPT015", file: "sqllangu.htm" },
  { topic: "chapter", section: "", title: "Server-Side Programming: PL/SQL and Java", anchor: "CNCPT036", file: "srvrside.htm" },
  { topic: "chapter", section: "", title: "Data Concurrency and Consistency ", anchor: "CNCPT020", file: "consist.htm" },
  { topic: "chapter", section: "", title: "Transactions ", anchor: "CNCPT016", file: "transact.htm" },
  { topic: "chapter", section: "", title: "Physical Storage Structures", anchor: "CNCPT003", file: "physical.htm" },
  { topic: "chapter", section: "", title: "Logical Storage Structures", anchor: "CNCPT004", file: "logical.htm" },
  { topic: "chapter", section: "", title: "Oracle Database Instance", anchor: "CNCPT005", file: "startup.htm" },
  { topic: "chapter", section: "", title: "Memory Architecture", anchor: "CNCPT007", file: "memory.htm" },
  { topic: "chapter", section: "", title: "Process Architecture", anchor: "CNCPT008", file: "process.htm" },
  { topic: "chapter", section: "", title: "Application and Networking Architecture", anchor: "CNCPT006", file: "dist_pro.htm" },
  { topic: "chapter", section: "", title: "Introduction to the Multitenant Architecture ", anchor: "CNCPT89234", file: "cdbovrvw.htm" },
  { topic: "chapter", section: "", title: "Overview of the Multitenant Architecture ", anchor: "CNCPT89248", file: "cdblogic.htm" },
  { topic: "chapter", section: "", title: "Topics for Database Administrators and Developers ", anchor: "CNCPT89272", file: "cmntopc.htm" },
  { topic: "chapter", section: "", title: "Concepts for Database Administrators", anchor: "CNCPT827", file: "cncptdba.htm" },
  { topic: "chapter", section: "", title: "Concepts for Database Developers ", anchor: "CNCPT89121", file: "cncptdev.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "CNCPT89131", file: "glossary.htm" },
  { } ];
