var chapters = [
  { topic: "chapter", section: "1", title: "Overview of the Oracle Database Gateway Installation", anchor: "OTGIW100", file: "overview.htm" },
  { topic: "chapter", section: "2", title: "Installing Oracle Database Gateway for Sybase", anchor: "OTGIW200", file: "sybase.htm" },
  { topic: "chapter", section: "3", title: "Configuring Oracle Database Gateway for Sybase", anchor: "OTGIW300", file: "conf_sybase.htm" },
  { topic: "chapter", section: "4", title: "Installing Oracle Database Gateway for Informix", anchor: "OTGIW400", file: "installinformix.htm" },
  { topic: "chapter", section: "5", title: "Configuring Oracle Database Gateway for Informix", anchor: "OTGIW500", file: "configinformix.htm" },
  { topic: "chapter", section: "6", title: "Installing Oracle Database Gateway for Teradata", anchor: "OTGIW600", file: "teradata.htm" },
  { topic: "chapter", section: "7", title: "Configuring Oracle Database Gateway for Teradata", anchor: "OTGIW700", file: "conf_teradata.htm" },
  { topic: "chapter", section: "8", title: "Installing Oracle Database Gateway for SQL Server", anchor: "OTGIW800", file: "sqlserver.htm" },
  { topic: "chapter", section: "9", title: "Configuring Oracle Database Gateway for SQL Server", anchor: "OTGIW900", file: "conf_sql.htm" },
  { topic: "chapter", section: "10", title: "Installing Oracle Database Gateway for ODBC", anchor: "OTGIW230", file: "installodbc.htm" },
  { topic: "chapter", section: "11", title: "Configuring Oracle Database Gateway for ODBC", anchor: "OTGIW110", file: "configodbc.htm" },
  { topic: "chapter", section: "12", title: "Installing Oracle Database Gateway for DRDA", anchor: "OTGIW120", file: "drda_install.htm" },
  { topic: "chapter", section: "13", title: "Configuring the DRDA Server", anchor: "OTGIW130", file: "cfg_drda.htm" },
  { topic: "chapter", section: "14", title: "Configuring Oracle Database Gateway for DRDA", anchor: "OTGIW140", file: "cfg_gtwy.htm" },
  { topic: "chapter", section: "15", title: "Security Considerations", anchor: "OTGIW150", file: "security.htm" },
  { topic: "chapter", section: "16", title: "Migration From Previous Releases", anchor: "OTGIW160", file: "migrate.htm" },
  { topic: "chapter", section: "17", title: "Removing Oracle Database Gateway", anchor: "OTGIW1266", file: "uninstallgtw.htm" },
  { topic: "appendix", section: "A", title: "Using Response Files for Noninteractive Installation", anchor: "OTGIW180", file: "advance.htm" },
  { topic: "appendix", section: "B", title: "Oracle Database Gateway Troubleshooting", anchor: "OTGIW190", file: "ts.htm" },
  { topic: "appendix", section: "C", title: "Initialization Parameters", anchor: "OTGIW240", file: "apd.htm" },
  { topic: "appendix", section: "D", title: "Configuration Worksheet for DRDA", anchor: "OTGIW210", file: "a_wrksht.htm" },
  { } ];
