var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Multimedia", anchor: "AIVUG1000", file: "ch_intro.htm" },
  { topic: "chapter", section: "2", title: "Common Methods and Notes for Oracle Multimedia Object Types", anchor: "AIVUG3000", file: "ch_comref.htm" },
  { topic: "chapter", section: "3", title: "Oracle Multimedia ORDAudio Object Type", anchor: "AIVUG4000", file: "ch_audref.htm" },
  { topic: "chapter", section: "4", title: "Oracle Multimedia ORDDoc Object Type", anchor: "AIVUG5000", file: "ch_docref.htm" },
  { topic: "chapter", section: "5", title: "Oracle Multimedia ORDImage Object Type", anchor: "AIVUG6000", file: "ch_imgref.htm" },
  { topic: "chapter", section: "6", title: "Oracle Multimedia ORDVideo Object Type", anchor: "AIVUG8000", file: "ch_vidref.htm" },
  { topic: "chapter", section: "7", title: "Oracle Multimedia Relational Interface", anchor: "AIVUG9000", file: "ch_relatref.htm" },
  { topic: "chapter", section: "8", title: "Oracle Multimedia ORDSource Object Type", anchor: "AIVUG10000", file: "ch_sourcref.htm" },
  { topic: "appendix", section: "A", title: "Audio File and Compression Formats for Use With Oracle Multimedia", anchor: "AIVUG20000", file: "ap_audfmts.htm" },
  { topic: "appendix", section: "B", title: "Image File and Compression Formats for Use With Oracle Multimedia", anchor: "AIVUG30000", file: "ap_imgfmts.htm" },
  { topic: "appendix", section: "C", title: "Video File and Compression Formats for Use With Oracle Multimedia", anchor: "AIVUG40000", file: "ap_vidfmts.htm" },
  { topic: "appendix", section: "D", title: "Oracle Multimedia Image Processing", anchor: "AIVUG50000", file: "ap_imgproc.htm" },
  { topic: "appendix", section: "E", title: "Image Raw Pixel Format for Use With Oracle Multimedia", anchor: "AIVUG60000", file: "ap_imgraw.htm" },
  { topic: "appendix", section: "F", title: "Oracle Multimedia Metadata XML Schemas", anchor: "AIVUG65000", file: "ap_xmlschms.htm" },
  { topic: "appendix", section: "G", title: "Exceptions for Oracle Multimedia Objects", anchor: "AIVUG70000", file: "ap_excpts.htm" },
  { topic: "appendix", section: "H", title: "init( ) Methods for Oracle Multimedia Object Types", anchor: "AIVUG80868", file: "ap_cominits.htm" },
  { topic: "appendix", section: "I", title: "Oracle Multimedia SQL/MM Still Image Object Types", anchor: "AIVUG75000", file: "ap_stimgref.htm" },
  { topic: "appendix", section: "J", title: "Oracle Multimedia Deprecated API Components", anchor: "AIVUG80000", file: "ap_deprec.htm" },
  { } ];
