var chapters = [
  { topic: "chapter", section: "", title: "Concepts and Architecture", anchor: "DFSIG-GUID-76D0CE8D-F584-4D67-932F-B45D25834993", file: "concepts-and-architecture.htm" },
  { topic: "chapter", section: "", title: "	Oracle Database Installation and Deinstallation ", anchor: "DFSIG-GUID-91029BA0-D848-4713-AD44-1D319AB77E56", file: "oracle-database-installation-and-deinstallation.htm" },
  { topic: "chapter", section: "", title: "About Creating a Database", anchor: "DFSIG-GUID-0391082C-4A8D-4F78-851A-730D9E1EC1B5", file: "about-creating-a-database.htm" },
  { topic: "chapter", section: "", title: "About Upgrading a Database", anchor: "DFSIG-GUID-ADA24BED-B5B6-4B24-9876-6D55C32FDB4E", file: "about-upgrading-a-database.htm" },
  { topic: "chapter", section: "", title: "Administering Oracle Database ", anchor: "DFSIG-GUID-90ECA63F-232C-493C-9707-AFDC2857A149", file: "administering-oracle-database.htm" },
  { topic: "chapter", section: "", title: " Oracle Database Utilities", anchor: "DFSIG197", file: "oracle-database-utilities.htm" },
  { topic: "chapter", section: "", title: "	Backing Up and Recovering a Database", anchor: "DFSIG212", file: "backing-up-and-recovering-a-database.htm" },
  { topic: "chapter", section: "", title: "About Unified Auditing", anchor: "DFSIG-GUID-A731D30D-855E-4562-AE4D-89F0A9FE2D7E", file: "unified-auditing.htm" },
  { topic: "chapter", section: "", title: "Java in the Database", anchor: "DFSIG422", file: "java-in-the-database.htm" },
  { topic: "chapter", section: "", title: "Oracle Text", anchor: "DFSIG269", file: "oracle-text.htm" },
  { topic: "chapter", section: "", title: "	XML", anchor: "DFSIG281", file: "xml.htm" },
  { topic: "chapter", section: "", title: "	Oracle Net Services", anchor: "DFSIG247", file: "oracle-net-services.htm" },
  { topic: "chapter", section: "", title: "Database Applications", anchor: "DFSIG-GUID-41D56A81-E5F9-4EA2-BA40-FCF1F672FC33", file: "database-applications.htm" },
  { topic: "chapter", section: "", title: "External Procedures ", anchor: "DFSIG-GUID-C61A9DAF-FE6B-4B0E-B6D7-BA61B0ECE0D6", file: "external-procedures.htm" },
  { topic: "chapter", section: "", title: " Globalization Support", anchor: "DFSIG-GUID-10519585-9D0B-49BE-8093-51A17421E39F", file: "globalization-support.htm" },
  { topic: "appendix", section: "", title: "Oracle Error Messages for BS2000", anchor: "DFSIG310", file: "oracle-error-messages-for-bs2000-osd.htm" },
  { topic: "appendix", section: "", title: "Oracle Environment Variables", anchor: "DFSIG311", file: "oracle-environment-variables.htm" },
  { topic: "appendix", section: "", title: "Initialization Parameters and the Parameter File", anchor: "DFSIG355", file: "initialization-parameters-and-the-parameter-file.htm" },
  { topic: "appendix", section: "", title: " Troubleshooting", anchor: "DFSIG366", file: "troubleshooting.htm" },
  { topic: "appendix", section: "", title: "File Types and Names Used by Oracle", anchor: "DFSIG377", file: "file-types-and-names-used-by-oracle.htm" },
  { } ];
