var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to High Availability Best Practices", anchor: "HABPT001", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Overview of Configuration Best Practices", anchor: "HABPT5145", file: "config_intro.htm" },
  { topic: "chapter", section: "3", title: "Configuring Storage", anchor: "HABPT4790", file: "config_storage.htm" },
  { topic: "chapter", section: "4", title: "Configuring Oracle Database", anchor: "HABPT4820", file: "config_db.htm" },
  { topic: "chapter", section: "5", title: "Configuring Oracle Database with Oracle Clusterware", anchor: "HABPT4849", file: "config_cw.htm" },
  { topic: "chapter", section: "6", title: "Configuring Oracle Database with Oracle RAC", anchor: "HABPT4865", file: "config_rac.htm" },
  { topic: "chapter", section: "7", title: "Configuring Backup and Recovery", anchor: "HABPT4929", file: "config_backuprec.htm" },
  { topic: "chapter", section: "8", title: "\u00A0Configuring Oracle Data Guard", anchor: "HABPT4876", file: "config_dg.htm" },
  { topic: "chapter", section: "9", title: "Configuring Oracle GoldenGate", anchor: "HABPT4962", file: "config_gg.htm" },
  { topic: "chapter", section: "10", title: "Client Failover Best Practices for Highly Available Oracle Databases", anchor: "HABPT4967", file: "config_fcf.htm" },
  { topic: "chapter", section: "11", title: "Monitoring for High Availability", anchor: "HABPT003", file: "monitor.htm" },
  { topic: "chapter", section: "12", title: "Recovering from Unscheduled Outages", anchor: "HABPT004", file: "outage.htm" },
  { topic: "chapter", section: "13", title: "Reducing Downtime for Planned Maintenance", anchor: "HABPT044", file: "schedule_outage.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "HABPT5215", file: "glossary.htm" },
  { } ];
