var chapters = [
  { topic: "chapter", section: "1", title: "Introduction", anchor: "LNPCB001", file: "pco01int.htm" },
  { topic: "chapter", section: "2", title: "Precompiler Concepts", anchor: "LNPCB002", file: "pco02prc.htm" },
  { topic: "chapter", section: "3", title: "Database Concepts", anchor: "LNPCB003", file: "pco03dbc.htm" },
  { topic: "chapter", section: "4", title: "Datatypes and Host Variables", anchor: "LNPCB004", file: "pco04dat.htm" },
  { topic: "chapter", section: "5", title: "Embedded SQL", anchor: "LNPCB005", file: "pco05sql.htm" },
  { topic: "chapter", section: "6", title: "Embedded PL/SQL", anchor: "LNPCB006", file: "pco06pls.htm" },
  { topic: "chapter", section: "7", title: "Host Tables", anchor: "LNPCB007", file: "pco07tab.htm" },
  { topic: "chapter", section: "8", title: "Error Handling and Diagnostics", anchor: "LNPCB008", file: "pco08err.htm" },
  { topic: "chapter", section: "9", title: "Oracle Dynamic SQL", anchor: "LNPCB009", file: "pco09dyn.htm" },
  { topic: "chapter", section: "10", title: "ANSI Dynamic SQL", anchor: "LNPCB010", file: "pco10ady.htm" },
  { topic: "chapter", section: "11", title: "Oracle Dynamic SQL: Method 4", anchor: "LNPCB011", file: "pco11ody.htm" },
  { topic: "chapter", section: "12", title: "Multithreaded Applications", anchor: "LNPCB785", file: "pco12thr.htm" },
  { topic: "chapter", section: "13", title: "Large Objects (LOBs)", anchor: "LNPCB013", file: "pco13lob.htm" },
  { topic: "chapter", section: "14", title: "Precompiler Options", anchor: "LNPCB014", file: "pco14opt.htm" },
  { topic: "appendix", section: "A", title: "Operating System Dependencies", anchor: "LNPCB016", file: "pcoabops.htm" },
  { topic: "appendix", section: "B", title: "Reserved Words, Keywords, and Namespaces", anchor: "LNPCB017", file: "pcoacres.htm" },
  { topic: "appendix", section: "C", title: "Performance Tuning", anchor: "LNPCB018", file: "pcoadtun.htm" },
  { topic: "appendix", section: "D", title: "Syntactic and Semantic Checking", anchor: "LNPCB019", file: "pcoaechk.htm" },
  { topic: "appendix", section: "E", title: "Embedded SQL Statements and Precompiler Directives", anchor: "LNPCB020", file: "pcoafemb.htm" },
  { topic: "appendix", section: "F", title: "Pro*COBOL for Windows", anchor: "LNPCB1743", file: "pcoawin.htm" },
  { } ];
